// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pgshard/v1/agent.proto

package pgshardv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_GetStatus_FullMethodName          = "/pgshard.v1.AgentService/GetStatus"
	AgentService_Promote_FullMethodName            = "/pgshard.v1.AgentService/Promote"
	AgentService_RejoinAsStandby_FullMethodName    = "/pgshard.v1.AgentService/RejoinAsStandby"
	AgentService_Fence_FullMethodName              = "/pgshard.v1.AgentService/Fence"
	AgentService_ReloadConfig_FullMethodName       = "/pgshard.v1.AgentService/ReloadConfig"
	AgentService_CreateRestorePoint_FullMethodName = "/pgshard.v1.AgentService/CreateRestorePoint"
	AgentService_SwitchWal_FullMethodName          = "/pgshard.v1.AgentService/SwitchWal"
	AgentService_RunBackup_FullMethodName          = "/pgshard.v1.AgentService/RunBackup"
	AgentService_RunRestore_FullMethodName         = "/pgshard.v1.AgentService/RunRestore"
	AgentService_StanzaCreate_FullMethodName       = "/pgshard.v1.AgentService/StanzaCreate"
	AgentService_StanzaCheck_FullMethodName        = "/pgshard.v1.AgentService/StanzaCheck"
	AgentService_PrepareSource_FullMethodName      = "/pgshard.v1.AgentService/PrepareSource"
	AgentService_StartWorkflow_FullMethodName      = "/pgshard.v1.AgentService/StartWorkflow"
	AgentService_StopWorkflow_FullMethodName       = "/pgshard.v1.AgentService/StopWorkflow"
	AgentService_WatchWorkflows_FullMethodName     = "/pgshard.v1.AgentService/WatchWorkflows"
	AgentService_Checkpoint_FullMethodName         = "/pgshard.v1.AgentService/Checkpoint"
	AgentService_EmitJournal_FullMethodName        = "/pgshard.v1.AgentService/EmitJournal"
	AgentService_ShardStream_FullMethodName        = "/pgshard.v1.AgentService/ShardStream"
	AgentService_DropSlot_FullMethodName           = "/pgshard.v1.AgentService/DropSlot"
	AgentService_ExecSchema_FullMethodName         = "/pgshard.v1.AgentService/ExecSchema"
	AgentService_MigrationStep_FullMethodName      = "/pgshard.v1.AgentService/MigrationStep"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Runs inside every Postgres pod (PID 1). mTLS; called by operator and router.
type AgentServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	RejoinAsStandby(ctx context.Context, in *RejoinAsStandbyRequest, opts ...grpc.CallOption) (*RejoinAsStandbyResponse, error)
	Fence(ctx context.Context, in *FenceRequest, opts ...grpc.CallOption) (*FenceResponse, error)
	ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error)
	CreateRestorePoint(ctx context.Context, in *CreateRestorePointRequest, opts ...grpc.CallOption) (*CreateRestorePointResponse, error)
	SwitchWal(ctx context.Context, in *SwitchWalRequest, opts ...grpc.CallOption) (*SwitchWalResponse, error)
	RunBackup(ctx context.Context, in *RunBackupRequest, opts ...grpc.CallOption) (*RunBackupResponse, error)
	RunRestore(ctx context.Context, in *RunRestoreRequest, opts ...grpc.CallOption) (*RunRestoreResponse, error)
	StanzaCreate(ctx context.Context, in *StanzaCreateRequest, opts ...grpc.CallOption) (*StanzaCreateResponse, error)
	StanzaCheck(ctx context.Context, in *StanzaCheckRequest, opts ...grpc.CallOption) (*StanzaCheckResponse, error)
	PrepareSource(ctx context.Context, in *PrepareSourceRequest, opts ...grpc.CallOption) (*PrepareSourceResponse, error)
	StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error)
	StopWorkflow(ctx context.Context, in *StopWorkflowRequest, opts ...grpc.CallOption) (*StopWorkflowResponse, error)
	WatchWorkflows(ctx context.Context, in *WatchWorkflowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchWorkflowsResponse], error)
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	EmitJournal(ctx context.Context, in *EmitJournalRequest, opts ...grpc.CallOption) (*EmitJournalResponse, error)
	ShardStream(ctx context.Context, in *ShardStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardStreamResponse], error)
	DropSlot(ctx context.Context, in *DropSlotRequest, opts ...grpc.CallOption) (*DropSlotResponse, error)
	ExecSchema(ctx context.Context, in *ExecSchemaRequest, opts ...grpc.CallOption) (*ExecSchemaResponse, error)
	MigrationStep(ctx context.Context, in *MigrationStepRequest, opts ...grpc.CallOption) (*MigrationStepResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, AgentService_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RejoinAsStandby(ctx context.Context, in *RejoinAsStandbyRequest, opts ...grpc.CallOption) (*RejoinAsStandbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejoinAsStandbyResponse)
	err := c.cc.Invoke(ctx, AgentService_RejoinAsStandby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Fence(ctx context.Context, in *FenceRequest, opts ...grpc.CallOption) (*FenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FenceResponse)
	err := c.cc.Invoke(ctx, AgentService_Fence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_ReloadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateRestorePoint(ctx context.Context, in *CreateRestorePointRequest, opts ...grpc.CallOption) (*CreateRestorePointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRestorePointResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateRestorePoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SwitchWal(ctx context.Context, in *SwitchWalRequest, opts ...grpc.CallOption) (*SwitchWalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchWalResponse)
	err := c.cc.Invoke(ctx, AgentService_SwitchWal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RunBackup(ctx context.Context, in *RunBackupRequest, opts ...grpc.CallOption) (*RunBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunBackupResponse)
	err := c.cc.Invoke(ctx, AgentService_RunBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RunRestore(ctx context.Context, in *RunRestoreRequest, opts ...grpc.CallOption) (*RunRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunRestoreResponse)
	err := c.cc.Invoke(ctx, AgentService_RunRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StanzaCreate(ctx context.Context, in *StanzaCreateRequest, opts ...grpc.CallOption) (*StanzaCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StanzaCreateResponse)
	err := c.cc.Invoke(ctx, AgentService_StanzaCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StanzaCheck(ctx context.Context, in *StanzaCheckRequest, opts ...grpc.CallOption) (*StanzaCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StanzaCheckResponse)
	err := c.cc.Invoke(ctx, AgentService_StanzaCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PrepareSource(ctx context.Context, in *PrepareSourceRequest, opts ...grpc.CallOption) (*PrepareSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareSourceResponse)
	err := c.cc.Invoke(ctx, AgentService_PrepareSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkflowResponse)
	err := c.cc.Invoke(ctx, AgentService_StartWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopWorkflow(ctx context.Context, in *StopWorkflowRequest, opts ...grpc.CallOption) (*StopWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopWorkflowResponse)
	err := c.cc.Invoke(ctx, AgentService_StopWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) WatchWorkflows(ctx context.Context, in *WatchWorkflowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchWorkflowsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_WatchWorkflows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchWorkflowsRequest, WatchWorkflowsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_WatchWorkflowsClient = grpc.ServerStreamingClient[WatchWorkflowsResponse]

func (c *agentServiceClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, AgentService_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) EmitJournal(ctx context.Context, in *EmitJournalRequest, opts ...grpc.CallOption) (*EmitJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitJournalResponse)
	err := c.cc.Invoke(ctx, AgentService_EmitJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ShardStream(ctx context.Context, in *ShardStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_ShardStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShardStreamRequest, ShardStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ShardStreamClient = grpc.ServerStreamingClient[ShardStreamResponse]

func (c *agentServiceClient) DropSlot(ctx context.Context, in *DropSlotRequest, opts ...grpc.CallOption) (*DropSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropSlotResponse)
	err := c.cc.Invoke(ctx, AgentService_DropSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecSchema(ctx context.Context, in *ExecSchemaRequest, opts ...grpc.CallOption) (*ExecSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecSchemaResponse)
	err := c.cc.Invoke(ctx, AgentService_ExecSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) MigrationStep(ctx context.Context, in *MigrationStepRequest, opts ...grpc.CallOption) (*MigrationStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationStepResponse)
	err := c.cc.Invoke(ctx, AgentService_MigrationStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// Runs inside every Postgres pod (PID 1). mTLS; called by operator and router.
type AgentServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	RejoinAsStandby(context.Context, *RejoinAsStandbyRequest) (*RejoinAsStandbyResponse, error)
	Fence(context.Context, *FenceRequest) (*FenceResponse, error)
	ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error)
	CreateRestorePoint(context.Context, *CreateRestorePointRequest) (*CreateRestorePointResponse, error)
	SwitchWal(context.Context, *SwitchWalRequest) (*SwitchWalResponse, error)
	RunBackup(context.Context, *RunBackupRequest) (*RunBackupResponse, error)
	RunRestore(context.Context, *RunRestoreRequest) (*RunRestoreResponse, error)
	StanzaCreate(context.Context, *StanzaCreateRequest) (*StanzaCreateResponse, error)
	StanzaCheck(context.Context, *StanzaCheckRequest) (*StanzaCheckResponse, error)
	PrepareSource(context.Context, *PrepareSourceRequest) (*PrepareSourceResponse, error)
	StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error)
	StopWorkflow(context.Context, *StopWorkflowRequest) (*StopWorkflowResponse, error)
	WatchWorkflows(*WatchWorkflowsRequest, grpc.ServerStreamingServer[WatchWorkflowsResponse]) error
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	EmitJournal(context.Context, *EmitJournalRequest) (*EmitJournalResponse, error)
	ShardStream(*ShardStreamRequest, grpc.ServerStreamingServer[ShardStreamResponse]) error
	DropSlot(context.Context, *DropSlotRequest) (*DropSlotResponse, error)
	ExecSchema(context.Context, *ExecSchemaRequest) (*ExecSchemaResponse, error)
	MigrationStep(context.Context, *MigrationStepRequest) (*MigrationStepResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAgentServiceServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedAgentServiceServer) RejoinAsStandby(context.Context, *RejoinAsStandbyRequest) (*RejoinAsStandbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejoinAsStandby not implemented")
}
func (UnimplementedAgentServiceServer) Fence(context.Context, *FenceRequest) (*FenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fence not implemented")
}
func (UnimplementedAgentServiceServer) ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedAgentServiceServer) CreateRestorePoint(context.Context, *CreateRestorePointRequest) (*CreateRestorePointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestorePoint not implemented")
}
func (UnimplementedAgentServiceServer) SwitchWal(context.Context, *SwitchWalRequest) (*SwitchWalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchWal not implemented")
}
func (UnimplementedAgentServiceServer) RunBackup(context.Context, *RunBackupRequest) (*RunBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunBackup not implemented")
}
func (UnimplementedAgentServiceServer) RunRestore(context.Context, *RunRestoreRequest) (*RunRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunRestore not implemented")
}
func (UnimplementedAgentServiceServer) StanzaCreate(context.Context, *StanzaCreateRequest) (*StanzaCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StanzaCreate not implemented")
}
func (UnimplementedAgentServiceServer) StanzaCheck(context.Context, *StanzaCheckRequest) (*StanzaCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StanzaCheck not implemented")
}
func (UnimplementedAgentServiceServer) PrepareSource(context.Context, *PrepareSourceRequest) (*PrepareSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareSource not implemented")
}
func (UnimplementedAgentServiceServer) StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWorkflow not implemented")
}
func (UnimplementedAgentServiceServer) StopWorkflow(context.Context, *StopWorkflowRequest) (*StopWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopWorkflow not implemented")
}
func (UnimplementedAgentServiceServer) WatchWorkflows(*WatchWorkflowsRequest, grpc.ServerStreamingServer[WatchWorkflowsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchWorkflows not implemented")
}
func (UnimplementedAgentServiceServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedAgentServiceServer) EmitJournal(context.Context, *EmitJournalRequest) (*EmitJournalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitJournal not implemented")
}
func (UnimplementedAgentServiceServer) ShardStream(*ShardStreamRequest, grpc.ServerStreamingServer[ShardStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ShardStream not implemented")
}
func (UnimplementedAgentServiceServer) DropSlot(context.Context, *DropSlotRequest) (*DropSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropSlot not implemented")
}
func (UnimplementedAgentServiceServer) ExecSchema(context.Context, *ExecSchemaRequest) (*ExecSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecSchema not implemented")
}
func (UnimplementedAgentServiceServer) MigrationStep(context.Context, *MigrationStepRequest) (*MigrationStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrationStep not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RejoinAsStandby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejoinAsStandbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RejoinAsStandby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RejoinAsStandby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RejoinAsStandby(ctx, req.(*RejoinAsStandbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Fence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Fence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Fence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Fence(ctx, req.(*FenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReloadConfig(ctx, req.(*ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateRestorePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestorePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateRestorePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateRestorePoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateRestorePoint(ctx, req.(*CreateRestorePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SwitchWal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchWalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SwitchWal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SwitchWal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SwitchWal(ctx, req.(*SwitchWalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RunBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RunBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RunBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RunBackup(ctx, req.(*RunBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RunRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RunRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RunRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RunRestore(ctx, req.(*RunRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StanzaCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StanzaCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StanzaCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StanzaCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StanzaCreate(ctx, req.(*StanzaCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StanzaCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StanzaCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StanzaCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StanzaCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StanzaCheck(ctx, req.(*StanzaCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PrepareSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PrepareSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PrepareSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PrepareSource(ctx, req.(*PrepareSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartWorkflow(ctx, req.(*StartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopWorkflow(ctx, req.(*StopWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_WatchWorkflows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchWorkflowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).WatchWorkflows(m, &grpc.GenericServerStream[WatchWorkflowsRequest, WatchWorkflowsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_WatchWorkflowsServer = grpc.ServerStreamingServer[WatchWorkflowsResponse]

func _AgentService_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_EmitJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).EmitJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_EmitJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).EmitJournal(ctx, req.(*EmitJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ShardStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShardStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ShardStream(m, &grpc.GenericServerStream[ShardStreamRequest, ShardStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ShardStreamServer = grpc.ServerStreamingServer[ShardStreamResponse]

func _AgentService_DropSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DropSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DropSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DropSlot(ctx, req.(*DropSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExecSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecSchema(ctx, req.(*ExecSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_MigrationStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).MigrationStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_MigrationStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).MigrationStep(ctx, req.(*MigrationStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pgshard.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _AgentService_GetStatus_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _AgentService_Promote_Handler,
		},
		{
			MethodName: "RejoinAsStandby",
			Handler:    _AgentService_RejoinAsStandby_Handler,
		},
		{
			MethodName: "Fence",
			Handler:    _AgentService_Fence_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _AgentService_ReloadConfig_Handler,
		},
		{
			MethodName: "CreateRestorePoint",
			Handler:    _AgentService_CreateRestorePoint_Handler,
		},
		{
			MethodName: "SwitchWal",
			Handler:    _AgentService_SwitchWal_Handler,
		},
		{
			MethodName: "RunBackup",
			Handler:    _AgentService_RunBackup_Handler,
		},
		{
			MethodName: "RunRestore",
			Handler:    _AgentService_RunRestore_Handler,
		},
		{
			MethodName: "StanzaCreate",
			Handler:    _AgentService_StanzaCreate_Handler,
		},
		{
			MethodName: "StanzaCheck",
			Handler:    _AgentService_StanzaCheck_Handler,
		},
		{
			MethodName: "PrepareSource",
			Handler:    _AgentService_PrepareSource_Handler,
		},
		{
			MethodName: "StartWorkflow",
			Handler:    _AgentService_StartWorkflow_Handler,
		},
		{
			MethodName: "StopWorkflow",
			Handler:    _AgentService_StopWorkflow_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _AgentService_Checkpoint_Handler,
		},
		{
			MethodName: "EmitJournal",
			Handler:    _AgentService_EmitJournal_Handler,
		},
		{
			MethodName: "DropSlot",
			Handler:    _AgentService_DropSlot_Handler,
		},
		{
			MethodName: "ExecSchema",
			Handler:    _AgentService_ExecSchema_Handler,
		},
		{
			MethodName: "MigrationStep",
			Handler:    _AgentService_MigrationStep_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchWorkflows",
			Handler:       _AgentService_WatchWorkflows_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ShardStream",
			Handler:       _AgentService_ShardStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pgshard/v1/agent.proto",
}
