// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pgshard/v1/common.proto

package pgshardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Which instance a logical-replication consumer attaches to.
type SourcePolicy int32

const (
	SourcePolicy_SOURCE_POLICY_UNSPECIFIED     SourcePolicy = 0
	SourcePolicy_SOURCE_POLICY_PRIMARY         SourcePolicy = 1
	SourcePolicy_SOURCE_POLICY_PREFER_STANDBY  SourcePolicy = 2
	SourcePolicy_SOURCE_POLICY_REQUIRE_STANDBY SourcePolicy = 3
)

// Enum value maps for SourcePolicy.
var (
	SourcePolicy_name = map[int32]string{
		0: "SOURCE_POLICY_UNSPECIFIED",
		1: "SOURCE_POLICY_PRIMARY",
		2: "SOURCE_POLICY_PREFER_STANDBY",
		3: "SOURCE_POLICY_REQUIRE_STANDBY",
	}
	SourcePolicy_value = map[string]int32{
		"SOURCE_POLICY_UNSPECIFIED":     0,
		"SOURCE_POLICY_PRIMARY":         1,
		"SOURCE_POLICY_PREFER_STANDBY":  2,
		"SOURCE_POLICY_REQUIRE_STANDBY": 3,
	}
)

func (x SourcePolicy) Enum() *SourcePolicy {
	p := new(SourcePolicy)
	*p = x
	return p
}

func (x SourcePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourcePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_common_proto_enumTypes[0].Descriptor()
}

func (SourcePolicy) Type() protoreflect.EnumType {
	return &file_pgshard_v1_common_proto_enumTypes[0]
}

func (x SourcePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourcePolicy.Descriptor instead.
func (SourcePolicy) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_common_proto_rawDescGZIP(), []int{0}
}

// Half-open range [start, end) over the 64-bit keyspace-id space.
// An absent end means +infinity.
type KeyRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"fixed64,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *uint64                `protobuf:"fixed64,2,opt,name=end,proto3,oneof" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRange) Reset() {
	*x = KeyRange{}
	mi := &file_pgshard_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRange) ProtoMessage() {}

func (x *KeyRange) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRange.ProtoReflect.Descriptor instead.
func (*KeyRange) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *KeyRange) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *KeyRange) GetEnd() uint64 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

type Lsn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lsn) Reset() {
	*x = Lsn{}
	mi := &file_pgshard_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lsn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lsn) ProtoMessage() {}

func (x *Lsn) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lsn.ProtoReflect.Descriptor instead.
func (*Lsn) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Lsn) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ShardRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Shard         string                 `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardRef) Reset() {
	*x = ShardRef{}
	mi := &file_pgshard_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRef) ProtoMessage() {}

func (x *ShardRef) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRef.ProtoReflect.Descriptor instead.
func (*ShardRef) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ShardRef) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ShardRef) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

type TableRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRef) Reset() {
	*x = TableRef{}
	mi := &file_pgshard_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRef) ProtoMessage() {}

func (x *TableRef) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRef.ProtoReflect.Descriptor instead.
func (*TableRef) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *TableRef) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *TableRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PgEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgEndpoint) Reset() {
	*x = PgEndpoint{}
	mi := &file_pgshard_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgEndpoint) ProtoMessage() {}

func (x *PgEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgEndpoint.ProtoReflect.Descriptor instead.
func (*PgEndpoint) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *PgEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PgEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PgEndpoint) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

var File_pgshard_v1_common_proto protoreflect.FileDescriptor

const file_pgshard_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x17pgshard/v1/common.proto\x12\n" +
	"pgshard.v1\"?\n" +
	"\bKeyRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x06R\x05start\x12\x15\n" +
	"\x03end\x18\x02 \x01(\x06H\x00R\x03end\x88\x01\x01B\x06\n" +
	"\x04_end\"\x1b\n" +
	"\x03Lsn\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\":\n" +
	"\bShardRef\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\tR\x05shard\"6\n" +
	"\bTableRef\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"P\n" +
	"\n" +
	"PgEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase*\x8d\x01\n" +
	"\fSourcePolicy\x12\x1d\n" +
	"\x19SOURCE_POLICY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SOURCE_POLICY_PRIMARY\x10\x01\x12 \n" +
	"\x1cSOURCE_POLICY_PREFER_STANDBY\x10\x02\x12!\n" +
	"\x1dSOURCE_POLICY_REQUIRE_STANDBY\x10\x03BFZDgithub.com/andrew01234567890/pgshard2/operator/internal/pb/pgshardv1b\x06proto3"

var (
	file_pgshard_v1_common_proto_rawDescOnce sync.Once
	file_pgshard_v1_common_proto_rawDescData []byte
)

func file_pgshard_v1_common_proto_rawDescGZIP() []byte {
	file_pgshard_v1_common_proto_rawDescOnce.Do(func() {
		file_pgshard_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pgshard_v1_common_proto_rawDesc), len(file_pgshard_v1_common_proto_rawDesc)))
	})
	return file_pgshard_v1_common_proto_rawDescData
}

var file_pgshard_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pgshard_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pgshard_v1_common_proto_goTypes = []any{
	(SourcePolicy)(0),  // 0: pgshard.v1.SourcePolicy
	(*KeyRange)(nil),   // 1: pgshard.v1.KeyRange
	(*Lsn)(nil),        // 2: pgshard.v1.Lsn
	(*ShardRef)(nil),   // 3: pgshard.v1.ShardRef
	(*TableRef)(nil),   // 4: pgshard.v1.TableRef
	(*PgEndpoint)(nil), // 5: pgshard.v1.PgEndpoint
}
var file_pgshard_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pgshard_v1_common_proto_init() }
func file_pgshard_v1_common_proto_init() {
	if File_pgshard_v1_common_proto != nil {
		return
	}
	file_pgshard_v1_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgshard_v1_common_proto_rawDesc), len(file_pgshard_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pgshard_v1_common_proto_goTypes,
		DependencyIndexes: file_pgshard_v1_common_proto_depIdxs,
		EnumInfos:         file_pgshard_v1_common_proto_enumTypes,
		MessageInfos:      file_pgshard_v1_common_proto_msgTypes,
	}.Build()
	File_pgshard_v1_common_proto = out.File
	file_pgshard_v1_common_proto_goTypes = nil
	file_pgshard_v1_common_proto_depIdxs = nil
}
