// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pgshard/v1/router_admin.proto

package pgshardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{0}
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *RouterState           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetStateResponse) GetState() *RouterState {
	if x != nil {
		return x.State
	}
	return nil
}

type GateState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Gate             *Gate                  `protobuf:"bytes,1,opt,name=gate,proto3" json:"gate,omitempty"`
	BufferedSessions uint32                 `protobuf:"varint,2,opt,name=buffered_sessions,json=bufferedSessions,proto3" json:"buffered_sessions,omitempty"`
	BufferedBytes    uint64                 `protobuf:"varint,3,opt,name=buffered_bytes,json=bufferedBytes,proto3" json:"buffered_bytes,omitempty"`
	Expired          bool                   `protobuf:"varint,4,opt,name=expired,proto3" json:"expired,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GateState) Reset() {
	*x = GateState{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateState) ProtoMessage() {}

func (x *GateState) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateState.ProtoReflect.Descriptor instead.
func (*GateState) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GateState) GetGate() *Gate {
	if x != nil {
		return x.Gate
	}
	return nil
}

func (x *GateState) GetBufferedSessions() uint32 {
	if x != nil {
		return x.BufferedSessions
	}
	return 0
}

func (x *GateState) GetBufferedBytes() uint64 {
	if x != nil {
		return x.BufferedBytes
	}
	return 0
}

func (x *GateState) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

type RouterState struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AckedEpoch uint64                 `protobuf:"varint,1,opt,name=acked_epoch,json=ackedEpoch,proto3" json:"acked_epoch,omitempty"`
	// No in-flight writes predate this epoch's gates.
	QuiescedEpoch      uint64       `protobuf:"varint,2,opt,name=quiesced_epoch,json=quiescedEpoch,proto3" json:"quiesced_epoch,omitempty"`
	TopologyGeneration uint64       `protobuf:"varint,3,opt,name=topology_generation,json=topologyGeneration,proto3" json:"topology_generation,omitempty"`
	Gates              []*GateState `protobuf:"bytes,4,rep,name=gates,proto3" json:"gates,omitempty"`
	ActiveSessions     uint32       `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RouterState) Reset() {
	*x = RouterState{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterState) ProtoMessage() {}

func (x *RouterState) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterState.ProtoReflect.Descriptor instead.
func (*RouterState) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RouterState) GetAckedEpoch() uint64 {
	if x != nil {
		return x.AckedEpoch
	}
	return 0
}

func (x *RouterState) GetQuiescedEpoch() uint64 {
	if x != nil {
		return x.QuiescedEpoch
	}
	return 0
}

func (x *RouterState) GetTopologyGeneration() uint64 {
	if x != nil {
		return x.TopologyGeneration
	}
	return 0
}

func (x *RouterState) GetGates() []*GateState {
	if x != nil {
		return x.Gates
	}
	return nil
}

func (x *RouterState) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

type WaitEpochRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitEpochRequest) Reset() {
	*x = WaitEpochRequest{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitEpochRequest) ProtoMessage() {}

func (x *WaitEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitEpochRequest.ProtoReflect.Descriptor instead.
func (*WaitEpochRequest) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{4}
}

func (x *WaitEpochRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *WaitEpochRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WaitEpochResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedEpoch    uint64                 `protobuf:"varint,1,opt,name=acked_epoch,json=ackedEpoch,proto3" json:"acked_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitEpochResponse) Reset() {
	*x = WaitEpochResponse{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitEpochResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitEpochResponse) ProtoMessage() {}

func (x *WaitEpochResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitEpochResponse.ProtoReflect.Descriptor instead.
func (*WaitEpochResponse) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{5}
}

func (x *WaitEpochResponse) GetAckedEpoch() uint64 {
	if x != nil {
		return x.AckedEpoch
	}
	return 0
}

type WaitQuiescedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitQuiescedRequest) Reset() {
	*x = WaitQuiescedRequest{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitQuiescedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitQuiescedRequest) ProtoMessage() {}

func (x *WaitQuiescedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitQuiescedRequest.ProtoReflect.Descriptor instead.
func (*WaitQuiescedRequest) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{6}
}

func (x *WaitQuiescedRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *WaitQuiescedRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WaitQuiescedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuiescedEpoch uint64                 `protobuf:"varint,1,opt,name=quiesced_epoch,json=quiescedEpoch,proto3" json:"quiesced_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitQuiescedResponse) Reset() {
	*x = WaitQuiescedResponse{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitQuiescedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitQuiescedResponse) ProtoMessage() {}

func (x *WaitQuiescedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitQuiescedResponse.ProtoReflect.Descriptor instead.
func (*WaitQuiescedResponse) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{7}
}

func (x *WaitQuiescedResponse) GetQuiescedEpoch() uint64 {
	if x != nil {
		return x.QuiescedEpoch
	}
	return 0
}

type GateCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gate          *Gate                  `protobuf:"bytes,1,opt,name=gate,proto3" json:"gate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateCloseRequest) Reset() {
	*x = GateCloseRequest{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateCloseRequest) ProtoMessage() {}

func (x *GateCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateCloseRequest.ProtoReflect.Descriptor instead.
func (*GateCloseRequest) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GateCloseRequest) GetGate() *Gate {
	if x != nil {
		return x.Gate
	}
	return nil
}

type GateCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateCloseResponse) Reset() {
	*x = GateCloseResponse{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateCloseResponse) ProtoMessage() {}

func (x *GateCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateCloseResponse.ProtoReflect.Descriptor instead.
func (*GateCloseResponse) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{9}
}

// Opening uses the min_topology_generation stored on the closed gate itself
// (topology.proto Gate); the request cannot lower it.
type GateOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GateId        string                 `protobuf:"bytes,1,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateOpenRequest) Reset() {
	*x = GateOpenRequest{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateOpenRequest) ProtoMessage() {}

func (x *GateOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateOpenRequest.ProtoReflect.Descriptor instead.
func (*GateOpenRequest) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GateOpenRequest) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

type GateOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateOpenResponse) Reset() {
	*x = GateOpenResponse{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateOpenResponse) ProtoMessage() {}

func (x *GateOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateOpenResponse.ProtoReflect.Descriptor instead.
func (*GateOpenResponse) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{11}
}

type FlushPlanCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushPlanCacheRequest) Reset() {
	*x = FlushPlanCacheRequest{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushPlanCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushPlanCacheRequest) ProtoMessage() {}

func (x *FlushPlanCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushPlanCacheRequest.ProtoReflect.Descriptor instead.
func (*FlushPlanCacheRequest) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{12}
}

type FlushPlanCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evicted       uint64                 `protobuf:"varint,1,opt,name=evicted,proto3" json:"evicted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushPlanCacheResponse) Reset() {
	*x = FlushPlanCacheResponse{}
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushPlanCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushPlanCacheResponse) ProtoMessage() {}

func (x *FlushPlanCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_router_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushPlanCacheResponse.ProtoReflect.Descriptor instead.
func (*FlushPlanCacheResponse) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_router_admin_proto_rawDescGZIP(), []int{13}
}

func (x *FlushPlanCacheResponse) GetEvicted() uint64 {
	if x != nil {
		return x.Evicted
	}
	return 0
}

var File_pgshard_v1_router_admin_proto protoreflect.FileDescriptor

const file_pgshard_v1_router_admin_proto_rawDesc = "" +
	"\n" +
	"\x1dpgshard/v1/router_admin.proto\x12\n" +
	"pgshard.v1\x1a\x19pgshard/v1/topology.proto\"\x11\n" +
	"\x0fGetStateRequest\"A\n" +
	"\x10GetStateResponse\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.pgshard.v1.RouterStateR\x05state\"\x9f\x01\n" +
	"\tGateState\x12$\n" +
	"\x04gate\x18\x01 \x01(\v2\x10.pgshard.v1.GateR\x04gate\x12+\n" +
	"\x11buffered_sessions\x18\x02 \x01(\rR\x10bufferedSessions\x12%\n" +
	"\x0ebuffered_bytes\x18\x03 \x01(\x04R\rbufferedBytes\x12\x18\n" +
	"\aexpired\x18\x04 \x01(\bR\aexpired\"\xdc\x01\n" +
	"\vRouterState\x12\x1f\n" +
	"\vacked_epoch\x18\x01 \x01(\x04R\n" +
	"ackedEpoch\x12%\n" +
	"\x0equiesced_epoch\x18\x02 \x01(\x04R\rquiescedEpoch\x12/\n" +
	"\x13topology_generation\x18\x03 \x01(\x04R\x12topologyGeneration\x12+\n" +
	"\x05gates\x18\x04 \x03(\v2\x15.pgshard.v1.GateStateR\x05gates\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\rR\x0eactiveSessions\"G\n" +
	"\x10WaitEpochRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"4\n" +
	"\x11WaitEpochResponse\x12\x1f\n" +
	"\vacked_epoch\x18\x01 \x01(\x04R\n" +
	"ackedEpoch\"J\n" +
	"\x13WaitQuiescedRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"=\n" +
	"\x14WaitQuiescedResponse\x12%\n" +
	"\x0equiesced_epoch\x18\x01 \x01(\x04R\rquiescedEpoch\"8\n" +
	"\x10GateCloseRequest\x12$\n" +
	"\x04gate\x18\x01 \x01(\v2\x10.pgshard.v1.GateR\x04gate\"\x13\n" +
	"\x11GateCloseResponse\"*\n" +
	"\x0fGateOpenRequest\x12\x17\n" +
	"\agate_id\x18\x01 \x01(\tR\x06gateId\"\x12\n" +
	"\x10GateOpenResponse\"\x17\n" +
	"\x15FlushPlanCacheRequest\"2\n" +
	"\x16FlushPlanCacheResponse\x12\x18\n" +
	"\aevicted\x18\x01 \x01(\x04R\aevicted2\xe2\x03\n" +
	"\x12RouterAdminService\x12E\n" +
	"\bGetState\x12\x1b.pgshard.v1.GetStateRequest\x1a\x1c.pgshard.v1.GetStateResponse\x12H\n" +
	"\tWaitEpoch\x12\x1c.pgshard.v1.WaitEpochRequest\x1a\x1d.pgshard.v1.WaitEpochResponse\x12Q\n" +
	"\fWaitQuiesced\x12\x1f.pgshard.v1.WaitQuiescedRequest\x1a .pgshard.v1.WaitQuiescedResponse\x12H\n" +
	"\tGateClose\x12\x1c.pgshard.v1.GateCloseRequest\x1a\x1d.pgshard.v1.GateCloseResponse\x12E\n" +
	"\bGateOpen\x12\x1b.pgshard.v1.GateOpenRequest\x1a\x1c.pgshard.v1.GateOpenResponse\x12W\n" +
	"\x0eFlushPlanCache\x12!.pgshard.v1.FlushPlanCacheRequest\x1a\".pgshard.v1.FlushPlanCacheResponseBFZDgithub.com/andrew01234567890/pgshard2/operator/internal/pb/pgshardv1b\x06proto3"

var (
	file_pgshard_v1_router_admin_proto_rawDescOnce sync.Once
	file_pgshard_v1_router_admin_proto_rawDescData []byte
)

func file_pgshard_v1_router_admin_proto_rawDescGZIP() []byte {
	file_pgshard_v1_router_admin_proto_rawDescOnce.Do(func() {
		file_pgshard_v1_router_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pgshard_v1_router_admin_proto_rawDesc), len(file_pgshard_v1_router_admin_proto_rawDesc)))
	})
	return file_pgshard_v1_router_admin_proto_rawDescData
}

var file_pgshard_v1_router_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pgshard_v1_router_admin_proto_goTypes = []any{
	(*GetStateRequest)(nil),        // 0: pgshard.v1.GetStateRequest
	(*GetStateResponse)(nil),       // 1: pgshard.v1.GetStateResponse
	(*GateState)(nil),              // 2: pgshard.v1.GateState
	(*RouterState)(nil),            // 3: pgshard.v1.RouterState
	(*WaitEpochRequest)(nil),       // 4: pgshard.v1.WaitEpochRequest
	(*WaitEpochResponse)(nil),      // 5: pgshard.v1.WaitEpochResponse
	(*WaitQuiescedRequest)(nil),    // 6: pgshard.v1.WaitQuiescedRequest
	(*WaitQuiescedResponse)(nil),   // 7: pgshard.v1.WaitQuiescedResponse
	(*GateCloseRequest)(nil),       // 8: pgshard.v1.GateCloseRequest
	(*GateCloseResponse)(nil),      // 9: pgshard.v1.GateCloseResponse
	(*GateOpenRequest)(nil),        // 10: pgshard.v1.GateOpenRequest
	(*GateOpenResponse)(nil),       // 11: pgshard.v1.GateOpenResponse
	(*FlushPlanCacheRequest)(nil),  // 12: pgshard.v1.FlushPlanCacheRequest
	(*FlushPlanCacheResponse)(nil), // 13: pgshard.v1.FlushPlanCacheResponse
	(*Gate)(nil),                   // 14: pgshard.v1.Gate
}
var file_pgshard_v1_router_admin_proto_depIdxs = []int32{
	3,  // 0: pgshard.v1.GetStateResponse.state:type_name -> pgshard.v1.RouterState
	14, // 1: pgshard.v1.GateState.gate:type_name -> pgshard.v1.Gate
	2,  // 2: pgshard.v1.RouterState.gates:type_name -> pgshard.v1.GateState
	14, // 3: pgshard.v1.GateCloseRequest.gate:type_name -> pgshard.v1.Gate
	0,  // 4: pgshard.v1.RouterAdminService.GetState:input_type -> pgshard.v1.GetStateRequest
	4,  // 5: pgshard.v1.RouterAdminService.WaitEpoch:input_type -> pgshard.v1.WaitEpochRequest
	6,  // 6: pgshard.v1.RouterAdminService.WaitQuiesced:input_type -> pgshard.v1.WaitQuiescedRequest
	8,  // 7: pgshard.v1.RouterAdminService.GateClose:input_type -> pgshard.v1.GateCloseRequest
	10, // 8: pgshard.v1.RouterAdminService.GateOpen:input_type -> pgshard.v1.GateOpenRequest
	12, // 9: pgshard.v1.RouterAdminService.FlushPlanCache:input_type -> pgshard.v1.FlushPlanCacheRequest
	1,  // 10: pgshard.v1.RouterAdminService.GetState:output_type -> pgshard.v1.GetStateResponse
	5,  // 11: pgshard.v1.RouterAdminService.WaitEpoch:output_type -> pgshard.v1.WaitEpochResponse
	7,  // 12: pgshard.v1.RouterAdminService.WaitQuiesced:output_type -> pgshard.v1.WaitQuiescedResponse
	9,  // 13: pgshard.v1.RouterAdminService.GateClose:output_type -> pgshard.v1.GateCloseResponse
	11, // 14: pgshard.v1.RouterAdminService.GateOpen:output_type -> pgshard.v1.GateOpenResponse
	13, // 15: pgshard.v1.RouterAdminService.FlushPlanCache:output_type -> pgshard.v1.FlushPlanCacheResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pgshard_v1_router_admin_proto_init() }
func file_pgshard_v1_router_admin_proto_init() {
	if File_pgshard_v1_router_admin_proto != nil {
		return
	}
	file_pgshard_v1_topology_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgshard_v1_router_admin_proto_rawDesc), len(file_pgshard_v1_router_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pgshard_v1_router_admin_proto_goTypes,
		DependencyIndexes: file_pgshard_v1_router_admin_proto_depIdxs,
		MessageInfos:      file_pgshard_v1_router_admin_proto_msgTypes,
	}.Build()
	File_pgshard_v1_router_admin_proto = out.File
	file_pgshard_v1_router_admin_proto_goTypes = nil
	file_pgshard_v1_router_admin_proto_depIdxs = nil
}
