// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pgshard/v1/router_admin.proto

package pgshardv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouterAdminService_GetState_FullMethodName       = "/pgshard.v1.RouterAdminService/GetState"
	RouterAdminService_WaitEpoch_FullMethodName      = "/pgshard.v1.RouterAdminService/WaitEpoch"
	RouterAdminService_WaitQuiesced_FullMethodName   = "/pgshard.v1.RouterAdminService/WaitQuiesced"
	RouterAdminService_GateClose_FullMethodName      = "/pgshard.v1.RouterAdminService/GateClose"
	RouterAdminService_GateOpen_FullMethodName       = "/pgshard.v1.RouterAdminService/GateOpen"
	RouterAdminService_FlushPlanCache_FullMethodName = "/pgshard.v1.RouterAdminService/FlushPlanCache"
)

// RouterAdminServiceClient is the client API for RouterAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Served by every router; called by the operator during failover, rollouts,
// reshard/DDL cutovers, and backup barriers.
type RouterAdminServiceClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	WaitEpoch(ctx context.Context, in *WaitEpochRequest, opts ...grpc.CallOption) (*WaitEpochResponse, error)
	WaitQuiesced(ctx context.Context, in *WaitQuiescedRequest, opts ...grpc.CallOption) (*WaitQuiescedResponse, error)
	GateClose(ctx context.Context, in *GateCloseRequest, opts ...grpc.CallOption) (*GateCloseResponse, error)
	GateOpen(ctx context.Context, in *GateOpenRequest, opts ...grpc.CallOption) (*GateOpenResponse, error)
	FlushPlanCache(ctx context.Context, in *FlushPlanCacheRequest, opts ...grpc.CallOption) (*FlushPlanCacheResponse, error)
}

type routerAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterAdminServiceClient(cc grpc.ClientConnInterface) RouterAdminServiceClient {
	return &routerAdminServiceClient{cc}
}

func (c *routerAdminServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, RouterAdminService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerAdminServiceClient) WaitEpoch(ctx context.Context, in *WaitEpochRequest, opts ...grpc.CallOption) (*WaitEpochResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitEpochResponse)
	err := c.cc.Invoke(ctx, RouterAdminService_WaitEpoch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerAdminServiceClient) WaitQuiesced(ctx context.Context, in *WaitQuiescedRequest, opts ...grpc.CallOption) (*WaitQuiescedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitQuiescedResponse)
	err := c.cc.Invoke(ctx, RouterAdminService_WaitQuiesced_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerAdminServiceClient) GateClose(ctx context.Context, in *GateCloseRequest, opts ...grpc.CallOption) (*GateCloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GateCloseResponse)
	err := c.cc.Invoke(ctx, RouterAdminService_GateClose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerAdminServiceClient) GateOpen(ctx context.Context, in *GateOpenRequest, opts ...grpc.CallOption) (*GateOpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GateOpenResponse)
	err := c.cc.Invoke(ctx, RouterAdminService_GateOpen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerAdminServiceClient) FlushPlanCache(ctx context.Context, in *FlushPlanCacheRequest, opts ...grpc.CallOption) (*FlushPlanCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushPlanCacheResponse)
	err := c.cc.Invoke(ctx, RouterAdminService_FlushPlanCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterAdminServiceServer is the server API for RouterAdminService service.
// All implementations must embed UnimplementedRouterAdminServiceServer
// for forward compatibility.
//
// Served by every router; called by the operator during failover, rollouts,
// reshard/DDL cutovers, and backup barriers.
type RouterAdminServiceServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	WaitEpoch(context.Context, *WaitEpochRequest) (*WaitEpochResponse, error)
	WaitQuiesced(context.Context, *WaitQuiescedRequest) (*WaitQuiescedResponse, error)
	GateClose(context.Context, *GateCloseRequest) (*GateCloseResponse, error)
	GateOpen(context.Context, *GateOpenRequest) (*GateOpenResponse, error)
	FlushPlanCache(context.Context, *FlushPlanCacheRequest) (*FlushPlanCacheResponse, error)
	mustEmbedUnimplementedRouterAdminServiceServer()
}

// UnimplementedRouterAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterAdminServiceServer struct{}

func (UnimplementedRouterAdminServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedRouterAdminServiceServer) WaitEpoch(context.Context, *WaitEpochRequest) (*WaitEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitEpoch not implemented")
}
func (UnimplementedRouterAdminServiceServer) WaitQuiesced(context.Context, *WaitQuiescedRequest) (*WaitQuiescedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitQuiesced not implemented")
}
func (UnimplementedRouterAdminServiceServer) GateClose(context.Context, *GateCloseRequest) (*GateCloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GateClose not implemented")
}
func (UnimplementedRouterAdminServiceServer) GateOpen(context.Context, *GateOpenRequest) (*GateOpenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GateOpen not implemented")
}
func (UnimplementedRouterAdminServiceServer) FlushPlanCache(context.Context, *FlushPlanCacheRequest) (*FlushPlanCacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushPlanCache not implemented")
}
func (UnimplementedRouterAdminServiceServer) mustEmbedUnimplementedRouterAdminServiceServer() {}
func (UnimplementedRouterAdminServiceServer) testEmbeddedByValue()                            {}

// UnsafeRouterAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterAdminServiceServer will
// result in compilation errors.
type UnsafeRouterAdminServiceServer interface {
	mustEmbedUnimplementedRouterAdminServiceServer()
}

func RegisterRouterAdminServiceServer(s grpc.ServiceRegistrar, srv RouterAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedRouterAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouterAdminService_ServiceDesc, srv)
}

func _RouterAdminService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterAdminServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterAdminService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterAdminServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterAdminService_WaitEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterAdminServiceServer).WaitEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterAdminService_WaitEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterAdminServiceServer).WaitEpoch(ctx, req.(*WaitEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterAdminService_WaitQuiesced_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitQuiescedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterAdminServiceServer).WaitQuiesced(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterAdminService_WaitQuiesced_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterAdminServiceServer).WaitQuiesced(ctx, req.(*WaitQuiescedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterAdminService_GateClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterAdminServiceServer).GateClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterAdminService_GateClose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterAdminServiceServer).GateClose(ctx, req.(*GateCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterAdminService_GateOpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateOpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterAdminServiceServer).GateOpen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterAdminService_GateOpen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterAdminServiceServer).GateOpen(ctx, req.(*GateOpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterAdminService_FlushPlanCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushPlanCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterAdminServiceServer).FlushPlanCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterAdminService_FlushPlanCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterAdminServiceServer).FlushPlanCache(ctx, req.(*FlushPlanCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouterAdminService_ServiceDesc is the grpc.ServiceDesc for RouterAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pgshard.v1.RouterAdminService",
	HandlerType: (*RouterAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _RouterAdminService_GetState_Handler,
		},
		{
			MethodName: "WaitEpoch",
			Handler:    _RouterAdminService_WaitEpoch_Handler,
		},
		{
			MethodName: "WaitQuiesced",
			Handler:    _RouterAdminService_WaitQuiesced_Handler,
		},
		{
			MethodName: "GateClose",
			Handler:    _RouterAdminService_GateClose_Handler,
		},
		{
			MethodName: "GateOpen",
			Handler:    _RouterAdminService_GateOpen_Handler,
		},
		{
			MethodName: "FlushPlanCache",
			Handler:    _RouterAdminService_FlushPlanCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pgshard/v1/router_admin.proto",
}
