// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pgshard/v1/topology.proto

package pgshardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardState int32

const (
	ShardState_SHARD_STATE_UNSPECIFIED ShardState = 0
	ShardState_SHARD_STATE_SERVING     ShardState = 1
	ShardState_SHARD_STATE_SEEDING     ShardState = 2
	ShardState_SHARD_STATE_READ_ONLY   ShardState = 3
	ShardState_SHARD_STATE_DRAINING    ShardState = 4
	ShardState_SHARD_STATE_HIDDEN      ShardState = 5
)

// Enum value maps for ShardState.
var (
	ShardState_name = map[int32]string{
		0: "SHARD_STATE_UNSPECIFIED",
		1: "SHARD_STATE_SERVING",
		2: "SHARD_STATE_SEEDING",
		3: "SHARD_STATE_READ_ONLY",
		4: "SHARD_STATE_DRAINING",
		5: "SHARD_STATE_HIDDEN",
	}
	ShardState_value = map[string]int32{
		"SHARD_STATE_UNSPECIFIED": 0,
		"SHARD_STATE_SERVING":     1,
		"SHARD_STATE_SEEDING":     2,
		"SHARD_STATE_READ_ONLY":   3,
		"SHARD_STATE_DRAINING":    4,
		"SHARD_STATE_HIDDEN":      5,
	}
)

func (x ShardState) Enum() *ShardState {
	p := new(ShardState)
	*p = x
	return p
}

func (x ShardState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardState) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_topology_proto_enumTypes[0].Descriptor()
}

func (ShardState) Type() protoreflect.EnumType {
	return &file_pgshard_v1_topology_proto_enumTypes[0]
}

func (x ShardState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardState.Descriptor instead.
func (ShardState) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{0}
}

type TableType int32

const (
	TableType_TABLE_TYPE_UNSPECIFIED TableType = 0
	TableType_TABLE_TYPE_SHARDED     TableType = 1
	// Lives in the system (unsharded) database.
	TableType_TABLE_TYPE_GLOBAL TableType = 2
)

// Enum value maps for TableType.
var (
	TableType_name = map[int32]string{
		0: "TABLE_TYPE_UNSPECIFIED",
		1: "TABLE_TYPE_SHARDED",
		2: "TABLE_TYPE_GLOBAL",
	}
	TableType_value = map[string]int32{
		"TABLE_TYPE_UNSPECIFIED": 0,
		"TABLE_TYPE_SHARDED":     1,
		"TABLE_TYPE_GLOBAL":      2,
	}
)

func (x TableType) Enum() *TableType {
	p := new(TableType)
	*p = x
	return p
}

func (x TableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableType) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_topology_proto_enumTypes[1].Descriptor()
}

func (TableType) Type() protoreflect.EnumType {
	return &file_pgshard_v1_topology_proto_enumTypes[1]
}

func (x TableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableType.Descriptor instead.
func (TableType) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{1}
}

type GateMode int32

const (
	GateMode_GATE_MODE_UNSPECIFIED GateMode = 0
	GateMode_GATE_MODE_WRITES_ONLY GateMode = 1
	GateMode_GATE_MODE_ALL         GateMode = 2
)

// Enum value maps for GateMode.
var (
	GateMode_name = map[int32]string{
		0: "GATE_MODE_UNSPECIFIED",
		1: "GATE_MODE_WRITES_ONLY",
		2: "GATE_MODE_ALL",
	}
	GateMode_value = map[string]int32{
		"GATE_MODE_UNSPECIFIED": 0,
		"GATE_MODE_WRITES_ONLY": 1,
		"GATE_MODE_ALL":         2,
	}
)

func (x GateMode) Enum() *GateMode {
	p := new(GateMode)
	*p = x
	return p
}

func (x GateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_topology_proto_enumTypes[2].Descriptor()
}

func (GateMode) Type() protoreflect.EnumType {
	return &file_pgshard_v1_topology_proto_enumTypes[2]
}

func (x GateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GateMode.Descriptor instead.
func (GateMode) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{2}
}

// Compiled routing view. In Kubernetes this mirrors the PgShardRouting CRD;
// in tests it is served from a static file. Routers and agents apply an
// update iff epoch > last applied epoch.
type Topology struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Bumps only on structural change (shard set or table catalog).
	TopologyGeneration uint64        `protobuf:"varint,2,opt,name=topology_generation,json=topologyGeneration,proto3" json:"topology_generation,omitempty"`
	WriteLeaseSeconds  uint32        `protobuf:"varint,3,opt,name=write_lease_seconds,json=writeLeaseSeconds,proto3" json:"write_lease_seconds,omitempty"`
	HashFunction       string        `protobuf:"bytes,4,opt,name=hash_function,json=hashFunction,proto3" json:"hash_function,omitempty"`
	Shards             []*ShardEntry `protobuf:"bytes,5,rep,name=shards,proto3" json:"shards,omitempty"`
	Tables             []*TableEntry `protobuf:"bytes,6,rep,name=tables,proto3" json:"tables,omitempty"`
	Gates              []*Gate       `protobuf:"bytes,7,rep,name=gates,proto3" json:"gates,omitempty"`
	SequenceEndpoint   *PgEndpoint   `protobuf:"bytes,8,opt,name=sequence_endpoint,json=sequenceEndpoint,proto3" json:"sequence_endpoint,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Topology) Reset() {
	*x = Topology{}
	mi := &file_pgshard_v1_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{0}
}

func (x *Topology) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Topology) GetTopologyGeneration() uint64 {
	if x != nil {
		return x.TopologyGeneration
	}
	return 0
}

func (x *Topology) GetWriteLeaseSeconds() uint32 {
	if x != nil {
		return x.WriteLeaseSeconds
	}
	return 0
}

func (x *Topology) GetHashFunction() string {
	if x != nil {
		return x.HashFunction
	}
	return ""
}

func (x *Topology) GetShards() []*ShardEntry {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *Topology) GetTables() []*TableEntry {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *Topology) GetGates() []*Gate {
	if x != nil {
		return x.Gates
	}
	return nil
}

func (x *Topology) GetSequenceEndpoint() *PgEndpoint {
	if x != nil {
		return x.SequenceEndpoint
	}
	return nil
}

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           string                 `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Endpoint      *PgEndpoint            `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CanRead       bool                   `protobuf:"varint,3,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_pgshard_v1_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{1}
}

func (x *Instance) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *Instance) GetEndpoint() *PgEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *Instance) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

type ShardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KeyRange      *KeyRange              `protobuf:"bytes,2,opt,name=key_range,json=keyRange,proto3" json:"key_range,omitempty"`
	State         ShardState             `protobuf:"varint,3,opt,name=state,proto3,enum=pgshard.v1.ShardState" json:"state,omitempty"`
	Primary       *Instance              `protobuf:"bytes,4,opt,name=primary,proto3" json:"primary,omitempty"`
	Replicas      []*Instance            `protobuf:"bytes,5,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardEntry) Reset() {
	*x = ShardEntry{}
	mi := &file_pgshard_v1_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardEntry) ProtoMessage() {}

func (x *ShardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardEntry.ProtoReflect.Descriptor instead.
func (*ShardEntry) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{2}
}

func (x *ShardEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShardEntry) GetKeyRange() *KeyRange {
	if x != nil {
		return x.KeyRange
	}
	return nil
}

func (x *ShardEntry) GetState() ShardState {
	if x != nil {
		return x.State
	}
	return ShardState_SHARD_STATE_UNSPECIFIED
}

func (x *ShardEntry) GetPrimary() *Instance {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *ShardEntry) GetReplicas() []*Instance {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type SequenceBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Sequence      string                 `protobuf:"bytes,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceBinding) Reset() {
	*x = SequenceBinding{}
	mi := &file_pgshard_v1_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceBinding) ProtoMessage() {}

func (x *SequenceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceBinding.ProtoReflect.Descriptor instead.
func (*SequenceBinding) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{3}
}

func (x *SequenceBinding) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *SequenceBinding) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

type TableEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Table           *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Type            TableType              `protobuf:"varint,2,opt,name=type,proto3,enum=pgshard.v1.TableType" json:"type,omitempty"`
	ShardKeyColumns []string               `protobuf:"bytes,3,rep,name=shard_key_columns,json=shardKeyColumns,proto3" json:"shard_key_columns,omitempty"`
	Sequences       []*SequenceBinding     `protobuf:"bytes,4,rep,name=sequences,proto3" json:"sequences,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TableEntry) Reset() {
	*x = TableEntry{}
	mi := &file_pgshard_v1_topology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableEntry) ProtoMessage() {}

func (x *TableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_topology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableEntry.ProtoReflect.Descriptor instead.
func (*TableEntry) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{4}
}

func (x *TableEntry) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *TableEntry) GetType() TableType {
	if x != nil {
		return x.Type
	}
	return TableType_TABLE_TYPE_UNSPECIFIED
}

func (x *TableEntry) GetShardKeyColumns() []string {
	if x != nil {
		return x.ShardKeyColumns
	}
	return nil
}

func (x *TableEntry) GetSequences() []*SequenceBinding {
	if x != nil {
		return x.Sequences
	}
	return nil
}

type GateScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*GateScope_All
	//	*GateScope_Table
	//	*GateScope_KeyRange
	Scope         isGateScope_Scope `protobuf_oneof:"scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateScope) Reset() {
	*x = GateScope{}
	mi := &file_pgshard_v1_topology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateScope) ProtoMessage() {}

func (x *GateScope) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_topology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateScope.ProtoReflect.Descriptor instead.
func (*GateScope) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{5}
}

func (x *GateScope) GetScope() isGateScope_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *GateScope) GetAll() bool {
	if x != nil {
		if x, ok := x.Scope.(*GateScope_All); ok {
			return x.All
		}
	}
	return false
}

func (x *GateScope) GetTable() *TableRef {
	if x != nil {
		if x, ok := x.Scope.(*GateScope_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *GateScope) GetKeyRange() *KeyRange {
	if x != nil {
		if x, ok := x.Scope.(*GateScope_KeyRange); ok {
			return x.KeyRange
		}
	}
	return nil
}

type isGateScope_Scope interface {
	isGateScope_Scope()
}

type GateScope_All struct {
	All bool `protobuf:"varint,1,opt,name=all,proto3,oneof"`
}

type GateScope_Table struct {
	Table *TableRef `protobuf:"bytes,2,opt,name=table,proto3,oneof"`
}

type GateScope_KeyRange struct {
	KeyRange *KeyRange `protobuf:"bytes,3,opt,name=key_range,json=keyRange,proto3,oneof"`
}

func (*GateScope_All) isGateScope_Scope() {}

func (*GateScope_Table) isGateScope_Scope() {}

func (*GateScope_KeyRange) isGateScope_Scope() {}

// Buffering directive. The deadline is absolute: when it passes without an
// explicit open, routers fail-safe UNGATE and resume prior routing —
// coordinators must treat an expired gate as an aborted cutover.
type Gate struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Scope    *GateScope             `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Mode     GateMode               `protobuf:"varint,3,opt,name=mode,proto3,enum=pgshard.v1.GateMode" json:"mode,omitempty"`
	Epoch    uint64                 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// On open, sessions replay only after the watched topology reaches this.
	MinTopologyGeneration uint64 `protobuf:"varint,6,opt,name=min_topology_generation,json=minTopologyGeneration,proto3" json:"min_topology_generation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Gate) Reset() {
	*x = Gate{}
	mi := &file_pgshard_v1_topology_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gate) ProtoMessage() {}

func (x *Gate) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_topology_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gate.ProtoReflect.Descriptor instead.
func (*Gate) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_topology_proto_rawDescGZIP(), []int{6}
}

func (x *Gate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gate) GetScope() *GateScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Gate) GetMode() GateMode {
	if x != nil {
		return x.Mode
	}
	return GateMode_GATE_MODE_UNSPECIFIED
}

func (x *Gate) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Gate) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Gate) GetMinTopologyGeneration() uint64 {
	if x != nil {
		return x.MinTopologyGeneration
	}
	return 0
}

var File_pgshard_v1_topology_proto protoreflect.FileDescriptor

const file_pgshard_v1_topology_proto_rawDesc = "" +
	"\n" +
	"\x19pgshard/v1/topology.proto\x12\n" +
	"pgshard.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17pgshard/v1/common.proto\"\xf3\x02\n" +
	"\bTopology\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12/\n" +
	"\x13topology_generation\x18\x02 \x01(\x04R\x12topologyGeneration\x12.\n" +
	"\x13write_lease_seconds\x18\x03 \x01(\rR\x11writeLeaseSeconds\x12#\n" +
	"\rhash_function\x18\x04 \x01(\tR\fhashFunction\x12.\n" +
	"\x06shards\x18\x05 \x03(\v2\x16.pgshard.v1.ShardEntryR\x06shards\x12.\n" +
	"\x06tables\x18\x06 \x03(\v2\x16.pgshard.v1.TableEntryR\x06tables\x12&\n" +
	"\x05gates\x18\a \x03(\v2\x10.pgshard.v1.GateR\x05gates\x12C\n" +
	"\x11sequence_endpoint\x18\b \x01(\v2\x16.pgshard.v1.PgEndpointR\x10sequenceEndpoint\"k\n" +
	"\bInstance\x12\x10\n" +
	"\x03pod\x18\x01 \x01(\tR\x03pod\x122\n" +
	"\bendpoint\x18\x02 \x01(\v2\x16.pgshard.v1.PgEndpointR\bendpoint\x12\x19\n" +
	"\bcan_read\x18\x03 \x01(\bR\acanRead\"\xe3\x01\n" +
	"\n" +
	"ShardEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\tkey_range\x18\x02 \x01(\v2\x14.pgshard.v1.KeyRangeR\bkeyRange\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.pgshard.v1.ShardStateR\x05state\x12.\n" +
	"\aprimary\x18\x04 \x01(\v2\x14.pgshard.v1.InstanceR\aprimary\x120\n" +
	"\breplicas\x18\x05 \x03(\v2\x14.pgshard.v1.InstanceR\breplicas\"E\n" +
	"\x0fSequenceBinding\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\tR\bsequence\"\xca\x01\n" +
	"\n" +
	"TableEntry\x12*\n" +
	"\x05table\x18\x01 \x01(\v2\x14.pgshard.v1.TableRefR\x05table\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.pgshard.v1.TableTypeR\x04type\x12*\n" +
	"\x11shard_key_columns\x18\x03 \x03(\tR\x0fshardKeyColumns\x129\n" +
	"\tsequences\x18\x04 \x03(\v2\x1b.pgshard.v1.SequenceBindingR\tsequences\"\x8b\x01\n" +
	"\tGateScope\x12\x12\n" +
	"\x03all\x18\x01 \x01(\bH\x00R\x03all\x12,\n" +
	"\x05table\x18\x02 \x01(\v2\x14.pgshard.v1.TableRefH\x00R\x05table\x123\n" +
	"\tkey_range\x18\x03 \x01(\v2\x14.pgshard.v1.KeyRangeH\x00R\bkeyRangeB\a\n" +
	"\x05scope\"\xf3\x01\n" +
	"\x04Gate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x05scope\x18\x02 \x01(\v2\x15.pgshard.v1.GateScopeR\x05scope\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.pgshard.v1.GateModeR\x04mode\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x04R\x05epoch\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x126\n" +
	"\x17min_topology_generation\x18\x06 \x01(\x04R\x15minTopologyGeneration*\xa8\x01\n" +
	"\n" +
	"ShardState\x12\x1b\n" +
	"\x17SHARD_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SHARD_STATE_SERVING\x10\x01\x12\x17\n" +
	"\x13SHARD_STATE_SEEDING\x10\x02\x12\x19\n" +
	"\x15SHARD_STATE_READ_ONLY\x10\x03\x12\x18\n" +
	"\x14SHARD_STATE_DRAINING\x10\x04\x12\x16\n" +
	"\x12SHARD_STATE_HIDDEN\x10\x05*V\n" +
	"\tTableType\x12\x1a\n" +
	"\x16TABLE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TABLE_TYPE_SHARDED\x10\x01\x12\x15\n" +
	"\x11TABLE_TYPE_GLOBAL\x10\x02*S\n" +
	"\bGateMode\x12\x19\n" +
	"\x15GATE_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15GATE_MODE_WRITES_ONLY\x10\x01\x12\x11\n" +
	"\rGATE_MODE_ALL\x10\x02BFZDgithub.com/andrew01234567890/pgshard2/operator/internal/pb/pgshardv1b\x06proto3"

var (
	file_pgshard_v1_topology_proto_rawDescOnce sync.Once
	file_pgshard_v1_topology_proto_rawDescData []byte
)

func file_pgshard_v1_topology_proto_rawDescGZIP() []byte {
	file_pgshard_v1_topology_proto_rawDescOnce.Do(func() {
		file_pgshard_v1_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pgshard_v1_topology_proto_rawDesc), len(file_pgshard_v1_topology_proto_rawDesc)))
	})
	return file_pgshard_v1_topology_proto_rawDescData
}

var file_pgshard_v1_topology_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pgshard_v1_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pgshard_v1_topology_proto_goTypes = []any{
	(ShardState)(0),               // 0: pgshard.v1.ShardState
	(TableType)(0),                // 1: pgshard.v1.TableType
	(GateMode)(0),                 // 2: pgshard.v1.GateMode
	(*Topology)(nil),              // 3: pgshard.v1.Topology
	(*Instance)(nil),              // 4: pgshard.v1.Instance
	(*ShardEntry)(nil),            // 5: pgshard.v1.ShardEntry
	(*SequenceBinding)(nil),       // 6: pgshard.v1.SequenceBinding
	(*TableEntry)(nil),            // 7: pgshard.v1.TableEntry
	(*GateScope)(nil),             // 8: pgshard.v1.GateScope
	(*Gate)(nil),                  // 9: pgshard.v1.Gate
	(*PgEndpoint)(nil),            // 10: pgshard.v1.PgEndpoint
	(*KeyRange)(nil),              // 11: pgshard.v1.KeyRange
	(*TableRef)(nil),              // 12: pgshard.v1.TableRef
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_pgshard_v1_topology_proto_depIdxs = []int32{
	5,  // 0: pgshard.v1.Topology.shards:type_name -> pgshard.v1.ShardEntry
	7,  // 1: pgshard.v1.Topology.tables:type_name -> pgshard.v1.TableEntry
	9,  // 2: pgshard.v1.Topology.gates:type_name -> pgshard.v1.Gate
	10, // 3: pgshard.v1.Topology.sequence_endpoint:type_name -> pgshard.v1.PgEndpoint
	10, // 4: pgshard.v1.Instance.endpoint:type_name -> pgshard.v1.PgEndpoint
	11, // 5: pgshard.v1.ShardEntry.key_range:type_name -> pgshard.v1.KeyRange
	0,  // 6: pgshard.v1.ShardEntry.state:type_name -> pgshard.v1.ShardState
	4,  // 7: pgshard.v1.ShardEntry.primary:type_name -> pgshard.v1.Instance
	4,  // 8: pgshard.v1.ShardEntry.replicas:type_name -> pgshard.v1.Instance
	12, // 9: pgshard.v1.TableEntry.table:type_name -> pgshard.v1.TableRef
	1,  // 10: pgshard.v1.TableEntry.type:type_name -> pgshard.v1.TableType
	6,  // 11: pgshard.v1.TableEntry.sequences:type_name -> pgshard.v1.SequenceBinding
	12, // 12: pgshard.v1.GateScope.table:type_name -> pgshard.v1.TableRef
	11, // 13: pgshard.v1.GateScope.key_range:type_name -> pgshard.v1.KeyRange
	8,  // 14: pgshard.v1.Gate.scope:type_name -> pgshard.v1.GateScope
	2,  // 15: pgshard.v1.Gate.mode:type_name -> pgshard.v1.GateMode
	13, // 16: pgshard.v1.Gate.deadline:type_name -> google.protobuf.Timestamp
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pgshard_v1_topology_proto_init() }
func file_pgshard_v1_topology_proto_init() {
	if File_pgshard_v1_topology_proto != nil {
		return
	}
	file_pgshard_v1_common_proto_init()
	file_pgshard_v1_topology_proto_msgTypes[5].OneofWrappers = []any{
		(*GateScope_All)(nil),
		(*GateScope_Table)(nil),
		(*GateScope_KeyRange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgshard_v1_topology_proto_rawDesc), len(file_pgshard_v1_topology_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pgshard_v1_topology_proto_goTypes,
		DependencyIndexes: file_pgshard_v1_topology_proto_depIdxs,
		EnumInfos:         file_pgshard_v1_topology_proto_enumTypes,
		MessageInfos:      file_pgshard_v1_topology_proto_msgTypes,
	}.Build()
	File_pgshard_v1_topology_proto = out.File
	file_pgshard_v1_topology_proto_goTypes = nil
	file_pgshard_v1_topology_proto_depIdxs = nil
}
