// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pgshard/v1/vstream.proto

package pgshardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartMode int32

const (
	StartMode_START_MODE_UNSPECIFIED         StartMode = 0
	StartMode_START_MODE_POSITION            StartMode = 1
	StartMode_START_MODE_LATEST              StartMode = 2
	StartMode_START_MODE_SNAPSHOT_AND_FOLLOW StartMode = 3
)

// Enum value maps for StartMode.
var (
	StartMode_name = map[int32]string{
		0: "START_MODE_UNSPECIFIED",
		1: "START_MODE_POSITION",
		2: "START_MODE_LATEST",
		3: "START_MODE_SNAPSHOT_AND_FOLLOW",
	}
	StartMode_value = map[string]int32{
		"START_MODE_UNSPECIFIED":         0,
		"START_MODE_POSITION":            1,
		"START_MODE_LATEST":              2,
		"START_MODE_SNAPSHOT_AND_FOLLOW": 3,
	}
)

func (x StartMode) Enum() *StartMode {
	p := new(StartMode)
	*p = x
	return p
}

func (x StartMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_vstream_proto_enumTypes[0].Descriptor()
}

func (StartMode) Type() protoreflect.EnumType {
	return &file_pgshard_v1_vstream_proto_enumTypes[0]
}

func (x StartMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartMode.Descriptor instead.
func (StartMode) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{0}
}

type VEventType int32

const (
	VEventType_V_EVENT_TYPE_UNSPECIFIED    VEventType = 0
	VEventType_V_EVENT_TYPE_BEGIN          VEventType = 1
	VEventType_V_EVENT_TYPE_FIELD          VEventType = 2
	VEventType_V_EVENT_TYPE_ROW            VEventType = 3
	VEventType_V_EVENT_TYPE_COMMIT         VEventType = 4
	VEventType_V_EVENT_TYPE_DDL            VEventType = 5
	VEventType_V_EVENT_TYPE_JOURNAL        VEventType = 6
	VEventType_V_EVENT_TYPE_VGTID          VEventType = 7
	VEventType_V_EVENT_TYPE_HEARTBEAT      VEventType = 8
	VEventType_V_EVENT_TYPE_COPY_COMPLETED VEventType = 9
)

// Enum value maps for VEventType.
var (
	VEventType_name = map[int32]string{
		0: "V_EVENT_TYPE_UNSPECIFIED",
		1: "V_EVENT_TYPE_BEGIN",
		2: "V_EVENT_TYPE_FIELD",
		3: "V_EVENT_TYPE_ROW",
		4: "V_EVENT_TYPE_COMMIT",
		5: "V_EVENT_TYPE_DDL",
		6: "V_EVENT_TYPE_JOURNAL",
		7: "V_EVENT_TYPE_VGTID",
		8: "V_EVENT_TYPE_HEARTBEAT",
		9: "V_EVENT_TYPE_COPY_COMPLETED",
	}
	VEventType_value = map[string]int32{
		"V_EVENT_TYPE_UNSPECIFIED":    0,
		"V_EVENT_TYPE_BEGIN":          1,
		"V_EVENT_TYPE_FIELD":          2,
		"V_EVENT_TYPE_ROW":            3,
		"V_EVENT_TYPE_COMMIT":         4,
		"V_EVENT_TYPE_DDL":            5,
		"V_EVENT_TYPE_JOURNAL":        6,
		"V_EVENT_TYPE_VGTID":          7,
		"V_EVENT_TYPE_HEARTBEAT":      8,
		"V_EVENT_TYPE_COPY_COMPLETED": 9,
	}
)

func (x VEventType) Enum() *VEventType {
	p := new(VEventType)
	*p = x
	return p
}

func (x VEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_vstream_proto_enumTypes[1].Descriptor()
}

func (VEventType) Type() protoreflect.EnumType {
	return &file_pgshard_v1_vstream_proto_enumTypes[1]
}

func (x VEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VEventType.Descriptor instead.
func (VEventType) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{1}
}

type RowOp int32

const (
	RowOp_ROW_OP_UNSPECIFIED RowOp = 0
	RowOp_ROW_OP_INSERT      RowOp = 1
	RowOp_ROW_OP_UPDATE      RowOp = 2
	RowOp_ROW_OP_DELETE      RowOp = 3
)

// Enum value maps for RowOp.
var (
	RowOp_name = map[int32]string{
		0: "ROW_OP_UNSPECIFIED",
		1: "ROW_OP_INSERT",
		2: "ROW_OP_UPDATE",
		3: "ROW_OP_DELETE",
	}
	RowOp_value = map[string]int32{
		"ROW_OP_UNSPECIFIED": 0,
		"ROW_OP_INSERT":      1,
		"ROW_OP_UPDATE":      2,
		"ROW_OP_DELETE":      3,
	}
)

func (x RowOp) Enum() *RowOp {
	p := new(RowOp)
	*p = x
	return p
}

func (x RowOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RowOp) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_vstream_proto_enumTypes[2].Descriptor()
}

func (RowOp) Type() protoreflect.EnumType {
	return &file_pgshard_v1_vstream_proto_enumTypes[2]
}

func (x RowOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RowOp.Descriptor instead.
func (RowOp) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{2}
}

// Position in the unified stream: one LSN per serving shard.
type VGtid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardGtids    []*ShardGtid           `protobuf:"bytes,1,rep,name=shard_gtids,json=shardGtids,proto3" json:"shard_gtids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VGtid) Reset() {
	*x = VGtid{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VGtid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VGtid) ProtoMessage() {}

func (x *VGtid) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VGtid.ProtoReflect.Descriptor instead.
func (*VGtid) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{0}
}

func (x *VGtid) GetShardGtids() []*ShardGtid {
	if x != nil {
		return x.ShardGtids
	}
	return nil
}

type ShardGtid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Shard string                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Lsn   *Lsn                   `protobuf:"bytes,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	// Tables whose snapshot copy already completed (SNAPSHOT_AND_FOLLOW resume).
	TablesCopied  []string `protobuf:"bytes,3,rep,name=tables_copied,json=tablesCopied,proto3" json:"tables_copied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardGtid) Reset() {
	*x = ShardGtid{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardGtid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardGtid) ProtoMessage() {}

func (x *ShardGtid) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardGtid.ProtoReflect.Descriptor instead.
func (*ShardGtid) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{1}
}

func (x *ShardGtid) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *ShardGtid) GetLsn() *Lsn {
	if x != nil {
		return x.Lsn
	}
	return nil
}

func (x *ShardGtid) GetTablesCopied() []string {
	if x != nil {
		return x.TablesCopied
	}
	return nil
}

type StreamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Mode           StartMode              `protobuf:"varint,2,opt,name=mode,proto3,enum=pgshard.v1.StartMode" json:"mode,omitempty"`
	Position       *VGtid                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	// Empty means all sharded tables.
	Tables        []*TableRef `protobuf:"bytes,4,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *StreamRequest) GetMode() StartMode {
	if x != nil {
		return x.Mode
	}
	return StartMode_START_MODE_UNSPECIFIED
}

func (x *StreamRequest) GetPosition() *VGtid {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *StreamRequest) GetTables() []*TableRef {
	if x != nil {
		return x.Tables
	}
	return nil
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *VEvent                `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{3}
}

func (x *StreamResponse) GetEvent() *VEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeOid       uint32                 `protobuf:"varint,2,opt,name=type_oid,json=typeOid,proto3" json:"type_oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{4}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetTypeOid() uint32 {
	if x != nil {
		return x.TypeOid
	}
	return 0
}

type FieldEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Fields        []*Field               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldEvent) Reset() {
	*x = FieldEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldEvent) ProtoMessage() {}

func (x *FieldEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldEvent.ProtoReflect.Descriptor instead.
func (*FieldEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{5}
}

func (x *FieldEvent) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *FieldEvent) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CellValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Null  bool                   `protobuf:"varint,1,opt,name=null,proto3" json:"null,omitempty"`
	// Postgres text-format encoding.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellValue) Reset() {
	*x = CellValue{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellValue) ProtoMessage() {}

func (x *CellValue) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellValue.ProtoReflect.Descriptor instead.
func (*CellValue) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{6}
}

func (x *CellValue) GetNull() bool {
	if x != nil {
		return x.Null
	}
	return false
}

func (x *CellValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Op            RowOp                  `protobuf:"varint,2,opt,name=op,proto3,enum=pgshard.v1.RowOp" json:"op,omitempty"`
	Before        []*CellValue           `protobuf:"bytes,3,rep,name=before,proto3" json:"before,omitempty"`
	After         []*CellValue           `protobuf:"bytes,4,rep,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowEvent) Reset() {
	*x = RowEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowEvent) ProtoMessage() {}

func (x *RowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowEvent.ProtoReflect.Descriptor instead.
func (*RowEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{7}
}

func (x *RowEvent) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *RowEvent) GetOp() RowOp {
	if x != nil {
		return x.Op
	}
	return RowOp_ROW_OP_UNSPECIFIED
}

func (x *RowEvent) GetBefore() []*CellValue {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *RowEvent) GetAfter() []*CellValue {
	if x != nil {
		return x.After
	}
	return nil
}

type DdlEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	MigrationId   string                 `protobuf:"bytes,2,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DdlEvent) Reset() {
	*x = DdlEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DdlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DdlEvent) ProtoMessage() {}

func (x *DdlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DdlEvent.ProtoReflect.Descriptor instead.
func (*DdlEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{8}
}

func (x *DdlEvent) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *DdlEvent) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

// Emitted at reshard cutover: the source shard's stream ends and continues
// on the successors at the recorded start LSNs.
type JournalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceShard   string                 `protobuf:"bytes,1,opt,name=source_shard,json=sourceShard,proto3" json:"source_shard,omitempty"`
	SourceLsn     *Lsn                   `protobuf:"bytes,2,opt,name=source_lsn,json=sourceLsn,proto3" json:"source_lsn,omitempty"`
	Successors    []*JournalSuccessor    `protobuf:"bytes,3,rep,name=successors,proto3" json:"successors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEvent) Reset() {
	*x = JournalEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEvent) ProtoMessage() {}

func (x *JournalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEvent.ProtoReflect.Descriptor instead.
func (*JournalEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{9}
}

func (x *JournalEvent) GetSourceShard() string {
	if x != nil {
		return x.SourceShard
	}
	return ""
}

func (x *JournalEvent) GetSourceLsn() *Lsn {
	if x != nil {
		return x.SourceLsn
	}
	return nil
}

func (x *JournalEvent) GetSuccessors() []*JournalSuccessor {
	if x != nil {
		return x.Successors
	}
	return nil
}

type JournalSuccessor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         string                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	KeyRange      *KeyRange              `protobuf:"bytes,2,opt,name=key_range,json=keyRange,proto3" json:"key_range,omitempty"`
	StartLsn      *Lsn                   `protobuf:"bytes,3,opt,name=start_lsn,json=startLsn,proto3" json:"start_lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalSuccessor) Reset() {
	*x = JournalSuccessor{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalSuccessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalSuccessor) ProtoMessage() {}

func (x *JournalSuccessor) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalSuccessor.ProtoReflect.Descriptor instead.
func (*JournalSuccessor) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{10}
}

func (x *JournalSuccessor) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *JournalSuccessor) GetKeyRange() *KeyRange {
	if x != nil {
		return x.KeyRange
	}
	return nil
}

func (x *JournalSuccessor) GetStartLsn() *Lsn {
	if x != nil {
		return x.StartLsn
	}
	return nil
}

type CopyCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyCompletedEvent) Reset() {
	*x = CopyCompletedEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyCompletedEvent) ProtoMessage() {}

func (x *CopyCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyCompletedEvent.ProtoReflect.Descriptor instead.
func (*CopyCompletedEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{11}
}

func (x *CopyCompletedEvent) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

type VEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Type       VEventType             `protobuf:"varint,1,opt,name=type,proto3,enum=pgshard.v1.VEventType" json:"type,omitempty"`
	Shard      string                 `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	CommitTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VEvent_Field
	//	*VEvent_Row
	//	*VEvent_Ddl
	//	*VEvent_Journal
	//	*VEvent_Vgtid
	//	*VEvent_CopyCompleted
	Payload       isVEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VEvent) Reset() {
	*x = VEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VEvent) ProtoMessage() {}

func (x *VEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VEvent.ProtoReflect.Descriptor instead.
func (*VEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{12}
}

func (x *VEvent) GetType() VEventType {
	if x != nil {
		return x.Type
	}
	return VEventType_V_EVENT_TYPE_UNSPECIFIED
}

func (x *VEvent) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *VEvent) GetCommitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTime
	}
	return nil
}

func (x *VEvent) GetPayload() isVEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VEvent) GetField() *FieldEvent {
	if x != nil {
		if x, ok := x.Payload.(*VEvent_Field); ok {
			return x.Field
		}
	}
	return nil
}

func (x *VEvent) GetRow() *RowEvent {
	if x != nil {
		if x, ok := x.Payload.(*VEvent_Row); ok {
			return x.Row
		}
	}
	return nil
}

func (x *VEvent) GetDdl() *DdlEvent {
	if x != nil {
		if x, ok := x.Payload.(*VEvent_Ddl); ok {
			return x.Ddl
		}
	}
	return nil
}

func (x *VEvent) GetJournal() *JournalEvent {
	if x != nil {
		if x, ok := x.Payload.(*VEvent_Journal); ok {
			return x.Journal
		}
	}
	return nil
}

func (x *VEvent) GetVgtid() *VGtid {
	if x != nil {
		if x, ok := x.Payload.(*VEvent_Vgtid); ok {
			return x.Vgtid
		}
	}
	return nil
}

func (x *VEvent) GetCopyCompleted() *CopyCompletedEvent {
	if x != nil {
		if x, ok := x.Payload.(*VEvent_CopyCompleted); ok {
			return x.CopyCompleted
		}
	}
	return nil
}

type isVEvent_Payload interface {
	isVEvent_Payload()
}

type VEvent_Field struct {
	Field *FieldEvent `protobuf:"bytes,4,opt,name=field,proto3,oneof"`
}

type VEvent_Row struct {
	Row *RowEvent `protobuf:"bytes,5,opt,name=row,proto3,oneof"`
}

type VEvent_Ddl struct {
	Ddl *DdlEvent `protobuf:"bytes,6,opt,name=ddl,proto3,oneof"`
}

type VEvent_Journal struct {
	Journal *JournalEvent `protobuf:"bytes,7,opt,name=journal,proto3,oneof"`
}

type VEvent_Vgtid struct {
	Vgtid *VGtid `protobuf:"bytes,8,opt,name=vgtid,proto3,oneof"`
}

type VEvent_CopyCompleted struct {
	CopyCompleted *CopyCompletedEvent `protobuf:"bytes,9,opt,name=copy_completed,json=copyCompleted,proto3,oneof"`
}

func (*VEvent_Field) isVEvent_Payload() {}

func (*VEvent_Row) isVEvent_Payload() {}

func (*VEvent_Ddl) isVEvent_Payload() {}

func (*VEvent_Journal) isVEvent_Payload() {}

func (*VEvent_Vgtid) isVEvent_Payload() {}

func (*VEvent_CopyCompleted) isVEvent_Payload() {}

var File_pgshard_v1_vstream_proto protoreflect.FileDescriptor

const file_pgshard_v1_vstream_proto_rawDesc = "" +
	"\n" +
	"\x18pgshard/v1/vstream.proto\x12\n" +
	"pgshard.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17pgshard/v1/common.proto\"?\n" +
	"\x05VGtid\x126\n" +
	"\vshard_gtids\x18\x01 \x03(\v2\x15.pgshard.v1.ShardGtidR\n" +
	"shardGtids\"i\n" +
	"\tShardGtid\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\tR\x05shard\x12!\n" +
	"\x03lsn\x18\x02 \x01(\v2\x0f.pgshard.v1.LsnR\x03lsn\x12#\n" +
	"\rtables_copied\x18\x03 \x03(\tR\ftablesCopied\"\xc0\x01\n" +
	"\rStreamRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.pgshard.v1.StartModeR\x04mode\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.pgshard.v1.VGtidR\bposition\x12,\n" +
	"\x06tables\x18\x04 \x03(\v2\x14.pgshard.v1.TableRefR\x06tables\":\n" +
	"\x0eStreamResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.pgshard.v1.VEventR\x05event\"6\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\btype_oid\x18\x02 \x01(\rR\atypeOid\"c\n" +
	"\n" +
	"FieldEvent\x12*\n" +
	"\x05table\x18\x01 \x01(\v2\x14.pgshard.v1.TableRefR\x05table\x12)\n" +
	"\x06fields\x18\x02 \x03(\v2\x11.pgshard.v1.FieldR\x06fields\"5\n" +
	"\tCellValue\x12\x12\n" +
	"\x04null\x18\x01 \x01(\bR\x04null\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xb5\x01\n" +
	"\bRowEvent\x12*\n" +
	"\x05table\x18\x01 \x01(\v2\x14.pgshard.v1.TableRefR\x05table\x12!\n" +
	"\x02op\x18\x02 \x01(\x0e2\x11.pgshard.v1.RowOpR\x02op\x12-\n" +
	"\x06before\x18\x03 \x03(\v2\x15.pgshard.v1.CellValueR\x06before\x12+\n" +
	"\x05after\x18\x04 \x03(\v2\x15.pgshard.v1.CellValueR\x05after\"?\n" +
	"\bDdlEvent\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12!\n" +
	"\fmigration_id\x18\x02 \x01(\tR\vmigrationId\"\x9f\x01\n" +
	"\fJournalEvent\x12!\n" +
	"\fsource_shard\x18\x01 \x01(\tR\vsourceShard\x12.\n" +
	"\n" +
	"source_lsn\x18\x02 \x01(\v2\x0f.pgshard.v1.LsnR\tsourceLsn\x12<\n" +
	"\n" +
	"successors\x18\x03 \x03(\v2\x1c.pgshard.v1.JournalSuccessorR\n" +
	"successors\"\x89\x01\n" +
	"\x10JournalSuccessor\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\tR\x05shard\x121\n" +
	"\tkey_range\x18\x02 \x01(\v2\x14.pgshard.v1.KeyRangeR\bkeyRange\x12,\n" +
	"\tstart_lsn\x18\x03 \x01(\v2\x0f.pgshard.v1.LsnR\bstartLsn\"@\n" +
	"\x12CopyCompletedEvent\x12*\n" +
	"\x05table\x18\x01 \x01(\v2\x14.pgshard.v1.TableRefR\x05table\"\xc0\x03\n" +
	"\x06VEvent\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.pgshard.v1.VEventTypeR\x04type\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\tR\x05shard\x12;\n" +
	"\vcommit_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"commitTime\x12.\n" +
	"\x05field\x18\x04 \x01(\v2\x16.pgshard.v1.FieldEventH\x00R\x05field\x12(\n" +
	"\x03row\x18\x05 \x01(\v2\x14.pgshard.v1.RowEventH\x00R\x03row\x12(\n" +
	"\x03ddl\x18\x06 \x01(\v2\x14.pgshard.v1.DdlEventH\x00R\x03ddl\x124\n" +
	"\ajournal\x18\a \x01(\v2\x18.pgshard.v1.JournalEventH\x00R\ajournal\x12)\n" +
	"\x05vgtid\x18\b \x01(\v2\x11.pgshard.v1.VGtidH\x00R\x05vgtid\x12G\n" +
	"\x0ecopy_completed\x18\t \x01(\v2\x1e.pgshard.v1.CopyCompletedEventH\x00R\rcopyCompletedB\t\n" +
	"\apayload*{\n" +
	"\tStartMode\x12\x1a\n" +
	"\x16START_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13START_MODE_POSITION\x10\x01\x12\x15\n" +
	"\x11START_MODE_LATEST\x10\x02\x12\"\n" +
	"\x1eSTART_MODE_SNAPSHOT_AND_FOLLOW\x10\x03*\x8e\x02\n" +
	"\n" +
	"VEventType\x12\x1c\n" +
	"\x18V_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12V_EVENT_TYPE_BEGIN\x10\x01\x12\x16\n" +
	"\x12V_EVENT_TYPE_FIELD\x10\x02\x12\x14\n" +
	"\x10V_EVENT_TYPE_ROW\x10\x03\x12\x17\n" +
	"\x13V_EVENT_TYPE_COMMIT\x10\x04\x12\x14\n" +
	"\x10V_EVENT_TYPE_DDL\x10\x05\x12\x18\n" +
	"\x14V_EVENT_TYPE_JOURNAL\x10\x06\x12\x16\n" +
	"\x12V_EVENT_TYPE_VGTID\x10\a\x12\x1a\n" +
	"\x16V_EVENT_TYPE_HEARTBEAT\x10\b\x12\x1f\n" +
	"\x1bV_EVENT_TYPE_COPY_COMPLETED\x10\t*X\n" +
	"\x05RowOp\x12\x16\n" +
	"\x12ROW_OP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rROW_OP_INSERT\x10\x01\x12\x11\n" +
	"\rROW_OP_UPDATE\x10\x02\x12\x11\n" +
	"\rROW_OP_DELETE\x10\x032S\n" +
	"\x0eVStreamService\x12A\n" +
	"\x06Stream\x12\x19.pgshard.v1.StreamRequest\x1a\x1a.pgshard.v1.StreamResponse0\x01BFZDgithub.com/andrew01234567890/pgshard2/operator/internal/pb/pgshardv1b\x06proto3"

var (
	file_pgshard_v1_vstream_proto_rawDescOnce sync.Once
	file_pgshard_v1_vstream_proto_rawDescData []byte
)

func file_pgshard_v1_vstream_proto_rawDescGZIP() []byte {
	file_pgshard_v1_vstream_proto_rawDescOnce.Do(func() {
		file_pgshard_v1_vstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pgshard_v1_vstream_proto_rawDesc), len(file_pgshard_v1_vstream_proto_rawDesc)))
	})
	return file_pgshard_v1_vstream_proto_rawDescData
}

var file_pgshard_v1_vstream_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pgshard_v1_vstream_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pgshard_v1_vstream_proto_goTypes = []any{
	(StartMode)(0),                // 0: pgshard.v1.StartMode
	(VEventType)(0),               // 1: pgshard.v1.VEventType
	(RowOp)(0),                    // 2: pgshard.v1.RowOp
	(*VGtid)(nil),                 // 3: pgshard.v1.VGtid
	(*ShardGtid)(nil),             // 4: pgshard.v1.ShardGtid
	(*StreamRequest)(nil),         // 5: pgshard.v1.StreamRequest
	(*StreamResponse)(nil),        // 6: pgshard.v1.StreamResponse
	(*Field)(nil),                 // 7: pgshard.v1.Field
	(*FieldEvent)(nil),            // 8: pgshard.v1.FieldEvent
	(*CellValue)(nil),             // 9: pgshard.v1.CellValue
	(*RowEvent)(nil),              // 10: pgshard.v1.RowEvent
	(*DdlEvent)(nil),              // 11: pgshard.v1.DdlEvent
	(*JournalEvent)(nil),          // 12: pgshard.v1.JournalEvent
	(*JournalSuccessor)(nil),      // 13: pgshard.v1.JournalSuccessor
	(*CopyCompletedEvent)(nil),    // 14: pgshard.v1.CopyCompletedEvent
	(*VEvent)(nil),                // 15: pgshard.v1.VEvent
	(*Lsn)(nil),                   // 16: pgshard.v1.Lsn
	(*TableRef)(nil),              // 17: pgshard.v1.TableRef
	(*KeyRange)(nil),              // 18: pgshard.v1.KeyRange
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_pgshard_v1_vstream_proto_depIdxs = []int32{
	4,  // 0: pgshard.v1.VGtid.shard_gtids:type_name -> pgshard.v1.ShardGtid
	16, // 1: pgshard.v1.ShardGtid.lsn:type_name -> pgshard.v1.Lsn
	0,  // 2: pgshard.v1.StreamRequest.mode:type_name -> pgshard.v1.StartMode
	3,  // 3: pgshard.v1.StreamRequest.position:type_name -> pgshard.v1.VGtid
	17, // 4: pgshard.v1.StreamRequest.tables:type_name -> pgshard.v1.TableRef
	15, // 5: pgshard.v1.StreamResponse.event:type_name -> pgshard.v1.VEvent
	17, // 6: pgshard.v1.FieldEvent.table:type_name -> pgshard.v1.TableRef
	7,  // 7: pgshard.v1.FieldEvent.fields:type_name -> pgshard.v1.Field
	17, // 8: pgshard.v1.RowEvent.table:type_name -> pgshard.v1.TableRef
	2,  // 9: pgshard.v1.RowEvent.op:type_name -> pgshard.v1.RowOp
	9,  // 10: pgshard.v1.RowEvent.before:type_name -> pgshard.v1.CellValue
	9,  // 11: pgshard.v1.RowEvent.after:type_name -> pgshard.v1.CellValue
	16, // 12: pgshard.v1.JournalEvent.source_lsn:type_name -> pgshard.v1.Lsn
	13, // 13: pgshard.v1.JournalEvent.successors:type_name -> pgshard.v1.JournalSuccessor
	18, // 14: pgshard.v1.JournalSuccessor.key_range:type_name -> pgshard.v1.KeyRange
	16, // 15: pgshard.v1.JournalSuccessor.start_lsn:type_name -> pgshard.v1.Lsn
	17, // 16: pgshard.v1.CopyCompletedEvent.table:type_name -> pgshard.v1.TableRef
	1,  // 17: pgshard.v1.VEvent.type:type_name -> pgshard.v1.VEventType
	19, // 18: pgshard.v1.VEvent.commit_time:type_name -> google.protobuf.Timestamp
	8,  // 19: pgshard.v1.VEvent.field:type_name -> pgshard.v1.FieldEvent
	10, // 20: pgshard.v1.VEvent.row:type_name -> pgshard.v1.RowEvent
	11, // 21: pgshard.v1.VEvent.ddl:type_name -> pgshard.v1.DdlEvent
	12, // 22: pgshard.v1.VEvent.journal:type_name -> pgshard.v1.JournalEvent
	3,  // 23: pgshard.v1.VEvent.vgtid:type_name -> pgshard.v1.VGtid
	14, // 24: pgshard.v1.VEvent.copy_completed:type_name -> pgshard.v1.CopyCompletedEvent
	5,  // 25: pgshard.v1.VStreamService.Stream:input_type -> pgshard.v1.StreamRequest
	6,  // 26: pgshard.v1.VStreamService.Stream:output_type -> pgshard.v1.StreamResponse
	26, // [26:27] is the sub-list for method output_type
	25, // [25:26] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_pgshard_v1_vstream_proto_init() }
func file_pgshard_v1_vstream_proto_init() {
	if File_pgshard_v1_vstream_proto != nil {
		return
	}
	file_pgshard_v1_common_proto_init()
	file_pgshard_v1_vstream_proto_msgTypes[12].OneofWrappers = []any{
		(*VEvent_Field)(nil),
		(*VEvent_Row)(nil),
		(*VEvent_Ddl)(nil),
		(*VEvent_Journal)(nil),
		(*VEvent_Vgtid)(nil),
		(*VEvent_CopyCompleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgshard_v1_vstream_proto_rawDesc), len(file_pgshard_v1_vstream_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pgshard_v1_vstream_proto_goTypes,
		DependencyIndexes: file_pgshard_v1_vstream_proto_depIdxs,
		EnumInfos:         file_pgshard_v1_vstream_proto_enumTypes,
		MessageInfos:      file_pgshard_v1_vstream_proto_msgTypes,
	}.Build()
	File_pgshard_v1_vstream_proto = out.File
	file_pgshard_v1_vstream_proto_goTypes = nil
	file_pgshard_v1_vstream_proto_depIdxs = nil
}
