// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pgshard/v1/vstream.proto

package pgshardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RowOp int32

const (
	RowOp_ROW_OP_UNSPECIFIED RowOp = 0
	RowOp_ROW_OP_INSERT      RowOp = 1
	RowOp_ROW_OP_UPDATE      RowOp = 2
	RowOp_ROW_OP_DELETE      RowOp = 3
)

// Enum value maps for RowOp.
var (
	RowOp_name = map[int32]string{
		0: "ROW_OP_UNSPECIFIED",
		1: "ROW_OP_INSERT",
		2: "ROW_OP_UPDATE",
		3: "ROW_OP_DELETE",
	}
	RowOp_value = map[string]int32{
		"ROW_OP_UNSPECIFIED": 0,
		"ROW_OP_INSERT":      1,
		"ROW_OP_UPDATE":      2,
		"ROW_OP_DELETE":      3,
	}
)

func (x RowOp) Enum() *RowOp {
	p := new(RowOp)
	*p = x
	return p
}

func (x RowOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RowOp) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_vstream_proto_enumTypes[0].Descriptor()
}

func (RowOp) Type() protoreflect.EnumType {
	return &file_pgshard_v1_vstream_proto_enumTypes[0]
}

func (x RowOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RowOp.Descriptor instead.
func (RowOp) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{0}
}

// Position in the unified stream: one entry per serving shard.
//
// Resume semantics: each lsn is the commit LSN of the last transaction that
// was fully delivered for that shard. Resuming from a VGtid delivers
// transactions whose commit LSN is strictly greater — never a duplicate of
// the recorded transaction, never a skip.
type VGtid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardGtids    []*ShardGtid           `protobuf:"bytes,1,rep,name=shard_gtids,json=shardGtids,proto3" json:"shard_gtids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VGtid) Reset() {
	*x = VGtid{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VGtid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VGtid) ProtoMessage() {}

func (x *VGtid) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VGtid.ProtoReflect.Descriptor instead.
func (*VGtid) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{0}
}

func (x *VGtid) GetShardGtids() []*ShardGtid {
	if x != nil {
		return x.ShardGtids
	}
	return nil
}

type ShardGtid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Shard string                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Lsn   *Lsn                   `protobuf:"bytes,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	// Tables whose snapshot copy already completed (snapshot_and_follow resume).
	TablesCopied  []*TableRef `protobuf:"bytes,3,rep,name=tables_copied,json=tablesCopied,proto3" json:"tables_copied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardGtid) Reset() {
	*x = ShardGtid{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardGtid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardGtid) ProtoMessage() {}

func (x *ShardGtid) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardGtid.ProtoReflect.Descriptor instead.
func (*ShardGtid) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{1}
}

func (x *ShardGtid) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *ShardGtid) GetLsn() *Lsn {
	if x != nil {
		return x.Lsn
	}
	return nil
}

func (x *ShardGtid) GetTablesCopied() []*TableRef {
	if x != nil {
		return x.TablesCopied
	}
	return nil
}

// Start at the current end of each shard's stream.
type LatestStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestStart) Reset() {
	*x = LatestStart{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestStart) ProtoMessage() {}

func (x *LatestStart) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestStart.ProtoReflect.Descriptor instead.
func (*LatestStart) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{2}
}

// Stream a consistent snapshot of the tables first, then follow.
type SnapshotAndFollowStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotAndFollowStart) Reset() {
	*x = SnapshotAndFollowStart{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotAndFollowStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotAndFollowStart) ProtoMessage() {}

func (x *SnapshotAndFollowStart) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotAndFollowStart.ProtoReflect.Descriptor instead.
func (*SnapshotAndFollowStart) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{3}
}

type StreamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// Empty means all sharded tables.
	Tables []*TableRef `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
	// An unset start is INVALID_ARGUMENT.
	//
	// Types that are valid to be assigned to Start:
	//
	//	*StreamRequest_Position
	//	*StreamRequest_Latest
	//	*StreamRequest_SnapshotAndFollow
	Start         isStreamRequest_Start `protobuf_oneof:"start"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *StreamRequest) GetTables() []*TableRef {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *StreamRequest) GetStart() isStreamRequest_Start {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *StreamRequest) GetPosition() *VGtid {
	if x != nil {
		if x, ok := x.Start.(*StreamRequest_Position); ok {
			return x.Position
		}
	}
	return nil
}

func (x *StreamRequest) GetLatest() *LatestStart {
	if x != nil {
		if x, ok := x.Start.(*StreamRequest_Latest); ok {
			return x.Latest
		}
	}
	return nil
}

func (x *StreamRequest) GetSnapshotAndFollow() *SnapshotAndFollowStart {
	if x != nil {
		if x, ok := x.Start.(*StreamRequest_SnapshotAndFollow); ok {
			return x.SnapshotAndFollow
		}
	}
	return nil
}

type isStreamRequest_Start interface {
	isStreamRequest_Start()
}

type StreamRequest_Position struct {
	// Resume strictly after this position (see VGtid).
	Position *VGtid `protobuf:"bytes,3,opt,name=position,proto3,oneof"`
}

type StreamRequest_Latest struct {
	Latest *LatestStart `protobuf:"bytes,4,opt,name=latest,proto3,oneof"`
}

type StreamRequest_SnapshotAndFollow struct {
	SnapshotAndFollow *SnapshotAndFollowStart `protobuf:"bytes,5,opt,name=snapshot_and_follow,json=snapshotAndFollow,proto3,oneof"`
}

func (*StreamRequest_Position) isStreamRequest_Start() {}

func (*StreamRequest_Latest) isStreamRequest_Start() {}

func (*StreamRequest_SnapshotAndFollow) isStreamRequest_Start() {}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *VEvent                `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{5}
}

func (x *StreamResponse) GetEvent() *VEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeOid       uint32                 `protobuf:"varint,2,opt,name=type_oid,json=typeOid,proto3" json:"type_oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{6}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetTypeOid() uint32 {
	if x != nil {
		return x.TypeOid
	}
	return 0
}

type FieldEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Fields        []*Field               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldEvent) Reset() {
	*x = FieldEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldEvent) ProtoMessage() {}

func (x *FieldEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldEvent.ProtoReflect.Descriptor instead.
func (*FieldEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{7}
}

func (x *FieldEvent) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *FieldEvent) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CellValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Null  bool                   `protobuf:"varint,1,opt,name=null,proto3" json:"null,omitempty"`
	// Postgres text-format encoding.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellValue) Reset() {
	*x = CellValue{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellValue) ProtoMessage() {}

func (x *CellValue) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellValue.ProtoReflect.Descriptor instead.
func (*CellValue) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{8}
}

func (x *CellValue) GetNull() bool {
	if x != nil {
		return x.Null
	}
	return false
}

func (x *CellValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Op            RowOp                  `protobuf:"varint,2,opt,name=op,proto3,enum=pgshard.v1.RowOp" json:"op,omitempty"`
	Before        []*CellValue           `protobuf:"bytes,3,rep,name=before,proto3" json:"before,omitempty"`
	After         []*CellValue           `protobuf:"bytes,4,rep,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowEvent) Reset() {
	*x = RowEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowEvent) ProtoMessage() {}

func (x *RowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowEvent.ProtoReflect.Descriptor instead.
func (*RowEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{9}
}

func (x *RowEvent) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *RowEvent) GetOp() RowOp {
	if x != nil {
		return x.Op
	}
	return RowOp_ROW_OP_UNSPECIFIED
}

func (x *RowEvent) GetBefore() []*CellValue {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *RowEvent) GetAfter() []*CellValue {
	if x != nil {
		return x.After
	}
	return nil
}

type BeginEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lsn           *Lsn                   `protobuf:"bytes,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginEvent) Reset() {
	*x = BeginEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginEvent) ProtoMessage() {}

func (x *BeginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginEvent.ProtoReflect.Descriptor instead.
func (*BeginEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{10}
}

func (x *BeginEvent) GetLsn() *Lsn {
	if x != nil {
		return x.Lsn
	}
	return nil
}

type CommitEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Commit LSN of the transaction; after delivering the matching VGtid this
	// becomes the shard's resume position.
	Lsn           *Lsn `protobuf:"bytes,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitEvent) Reset() {
	*x = CommitEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitEvent) ProtoMessage() {}

func (x *CommitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitEvent.ProtoReflect.Descriptor instead.
func (*CommitEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{11}
}

func (x *CommitEvent) GetLsn() *Lsn {
	if x != nil {
		return x.Lsn
	}
	return nil
}

type HeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{12}
}

type DdlEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	MigrationId   string                 `protobuf:"bytes,2,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DdlEvent) Reset() {
	*x = DdlEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DdlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DdlEvent) ProtoMessage() {}

func (x *DdlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DdlEvent.ProtoReflect.Descriptor instead.
func (*DdlEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{13}
}

func (x *DdlEvent) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *DdlEvent) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

// Emitted at reshard cutover: the source shard's stream ends and continues
// on the successors at the recorded start LSNs.
type JournalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceShard   string                 `protobuf:"bytes,1,opt,name=source_shard,json=sourceShard,proto3" json:"source_shard,omitempty"`
	SourceLsn     *Lsn                   `protobuf:"bytes,2,opt,name=source_lsn,json=sourceLsn,proto3" json:"source_lsn,omitempty"`
	Successors    []*JournalSuccessor    `protobuf:"bytes,3,rep,name=successors,proto3" json:"successors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEvent) Reset() {
	*x = JournalEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEvent) ProtoMessage() {}

func (x *JournalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEvent.ProtoReflect.Descriptor instead.
func (*JournalEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{14}
}

func (x *JournalEvent) GetSourceShard() string {
	if x != nil {
		return x.SourceShard
	}
	return ""
}

func (x *JournalEvent) GetSourceLsn() *Lsn {
	if x != nil {
		return x.SourceLsn
	}
	return nil
}

func (x *JournalEvent) GetSuccessors() []*JournalSuccessor {
	if x != nil {
		return x.Successors
	}
	return nil
}

type JournalSuccessor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         string                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	KeyRange      *KeyRange              `protobuf:"bytes,2,opt,name=key_range,json=keyRange,proto3" json:"key_range,omitempty"`
	StartLsn      *Lsn                   `protobuf:"bytes,3,opt,name=start_lsn,json=startLsn,proto3" json:"start_lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalSuccessor) Reset() {
	*x = JournalSuccessor{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalSuccessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalSuccessor) ProtoMessage() {}

func (x *JournalSuccessor) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalSuccessor.ProtoReflect.Descriptor instead.
func (*JournalSuccessor) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{15}
}

func (x *JournalSuccessor) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *JournalSuccessor) GetKeyRange() *KeyRange {
	if x != nil {
		return x.KeyRange
	}
	return nil
}

func (x *JournalSuccessor) GetStartLsn() *Lsn {
	if x != nil {
		return x.StartLsn
	}
	return nil
}

type CopyCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyCompletedEvent) Reset() {
	*x = CopyCompletedEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyCompletedEvent) ProtoMessage() {}

func (x *CopyCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyCompletedEvent.ProtoReflect.Descriptor instead.
func (*CopyCompletedEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{16}
}

func (x *CopyCompletedEvent) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

type VEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Shard      string                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	CommitTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*VEvent_Begin
	//	*VEvent_Field
	//	*VEvent_Row
	//	*VEvent_Commit
	//	*VEvent_Ddl
	//	*VEvent_Journal
	//	*VEvent_Vgtid
	//	*VEvent_Heartbeat
	//	*VEvent_CopyCompleted
	Event         isVEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VEvent) Reset() {
	*x = VEvent{}
	mi := &file_pgshard_v1_vstream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VEvent) ProtoMessage() {}

func (x *VEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_vstream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VEvent.ProtoReflect.Descriptor instead.
func (*VEvent) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_vstream_proto_rawDescGZIP(), []int{17}
}

func (x *VEvent) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *VEvent) GetCommitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTime
	}
	return nil
}

func (x *VEvent) GetEvent() isVEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *VEvent) GetBegin() *BeginEvent {
	if x != nil {
		if x, ok := x.Event.(*VEvent_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *VEvent) GetField() *FieldEvent {
	if x != nil {
		if x, ok := x.Event.(*VEvent_Field); ok {
			return x.Field
		}
	}
	return nil
}

func (x *VEvent) GetRow() *RowEvent {
	if x != nil {
		if x, ok := x.Event.(*VEvent_Row); ok {
			return x.Row
		}
	}
	return nil
}

func (x *VEvent) GetCommit() *CommitEvent {
	if x != nil {
		if x, ok := x.Event.(*VEvent_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *VEvent) GetDdl() *DdlEvent {
	if x != nil {
		if x, ok := x.Event.(*VEvent_Ddl); ok {
			return x.Ddl
		}
	}
	return nil
}

func (x *VEvent) GetJournal() *JournalEvent {
	if x != nil {
		if x, ok := x.Event.(*VEvent_Journal); ok {
			return x.Journal
		}
	}
	return nil
}

func (x *VEvent) GetVgtid() *VGtid {
	if x != nil {
		if x, ok := x.Event.(*VEvent_Vgtid); ok {
			return x.Vgtid
		}
	}
	return nil
}

func (x *VEvent) GetHeartbeat() *HeartbeatEvent {
	if x != nil {
		if x, ok := x.Event.(*VEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *VEvent) GetCopyCompleted() *CopyCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*VEvent_CopyCompleted); ok {
			return x.CopyCompleted
		}
	}
	return nil
}

type isVEvent_Event interface {
	isVEvent_Event()
}

type VEvent_Begin struct {
	Begin *BeginEvent `protobuf:"bytes,3,opt,name=begin,proto3,oneof"`
}

type VEvent_Field struct {
	Field *FieldEvent `protobuf:"bytes,4,opt,name=field,proto3,oneof"`
}

type VEvent_Row struct {
	Row *RowEvent `protobuf:"bytes,5,opt,name=row,proto3,oneof"`
}

type VEvent_Commit struct {
	Commit *CommitEvent `protobuf:"bytes,6,opt,name=commit,proto3,oneof"`
}

type VEvent_Ddl struct {
	Ddl *DdlEvent `protobuf:"bytes,7,opt,name=ddl,proto3,oneof"`
}

type VEvent_Journal struct {
	Journal *JournalEvent `protobuf:"bytes,8,opt,name=journal,proto3,oneof"`
}

type VEvent_Vgtid struct {
	Vgtid *VGtid `protobuf:"bytes,9,opt,name=vgtid,proto3,oneof"`
}

type VEvent_Heartbeat struct {
	Heartbeat *HeartbeatEvent `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

type VEvent_CopyCompleted struct {
	CopyCompleted *CopyCompletedEvent `protobuf:"bytes,11,opt,name=copy_completed,json=copyCompleted,proto3,oneof"`
}

func (*VEvent_Begin) isVEvent_Event() {}

func (*VEvent_Field) isVEvent_Event() {}

func (*VEvent_Row) isVEvent_Event() {}

func (*VEvent_Commit) isVEvent_Event() {}

func (*VEvent_Ddl) isVEvent_Event() {}

func (*VEvent_Journal) isVEvent_Event() {}

func (*VEvent_Vgtid) isVEvent_Event() {}

func (*VEvent_Heartbeat) isVEvent_Event() {}

func (*VEvent_CopyCompleted) isVEvent_Event() {}

var File_pgshard_v1_vstream_proto protoreflect.FileDescriptor

const file_pgshard_v1_vstream_proto_rawDesc = "" +
	"\n" +
	"\x18pgshard/v1/vstream.proto\x12\n" +
	"pgshard.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17pgshard/v1/common.proto\"?\n" +
	"\x05VGtid\x126\n" +
	"\vshard_gtids\x18\x01 \x03(\v2\x15.pgshard.v1.ShardGtidR\n" +
	"shardGtids\"\x7f\n" +
	"\tShardGtid\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\tR\x05shard\x12!\n" +
	"\x03lsn\x18\x02 \x01(\v2\x0f.pgshard.v1.LsnR\x03lsn\x129\n" +
	"\rtables_copied\x18\x03 \x03(\v2\x14.pgshard.v1.TableRefR\ftablesCopied\"\r\n" +
	"\vLatestStart\"\x18\n" +
	"\x16SnapshotAndFollowStart\"\xa9\x02\n" +
	"\rStreamRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12,\n" +
	"\x06tables\x18\x02 \x03(\v2\x14.pgshard.v1.TableRefR\x06tables\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x11.pgshard.v1.VGtidH\x00R\bposition\x121\n" +
	"\x06latest\x18\x04 \x01(\v2\x17.pgshard.v1.LatestStartH\x00R\x06latest\x12T\n" +
	"\x13snapshot_and_follow\x18\x05 \x01(\v2\".pgshard.v1.SnapshotAndFollowStartH\x00R\x11snapshotAndFollowB\a\n" +
	"\x05start\":\n" +
	"\x0eStreamResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.pgshard.v1.VEventR\x05event\"6\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\btype_oid\x18\x02 \x01(\rR\atypeOid\"c\n" +
	"\n" +
	"FieldEvent\x12*\n" +
	"\x05table\x18\x01 \x01(\v2\x14.pgshard.v1.TableRefR\x05table\x12)\n" +
	"\x06fields\x18\x02 \x03(\v2\x11.pgshard.v1.FieldR\x06fields\"5\n" +
	"\tCellValue\x12\x12\n" +
	"\x04null\x18\x01 \x01(\bR\x04null\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xb5\x01\n" +
	"\bRowEvent\x12*\n" +
	"\x05table\x18\x01 \x01(\v2\x14.pgshard.v1.TableRefR\x05table\x12!\n" +
	"\x02op\x18\x02 \x01(\x0e2\x11.pgshard.v1.RowOpR\x02op\x12-\n" +
	"\x06before\x18\x03 \x03(\v2\x15.pgshard.v1.CellValueR\x06before\x12+\n" +
	"\x05after\x18\x04 \x03(\v2\x15.pgshard.v1.CellValueR\x05after\"/\n" +
	"\n" +
	"BeginEvent\x12!\n" +
	"\x03lsn\x18\x01 \x01(\v2\x0f.pgshard.v1.LsnR\x03lsn\"0\n" +
	"\vCommitEvent\x12!\n" +
	"\x03lsn\x18\x01 \x01(\v2\x0f.pgshard.v1.LsnR\x03lsn\"\x10\n" +
	"\x0eHeartbeatEvent\"?\n" +
	"\bDdlEvent\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12!\n" +
	"\fmigration_id\x18\x02 \x01(\tR\vmigrationId\"\x9f\x01\n" +
	"\fJournalEvent\x12!\n" +
	"\fsource_shard\x18\x01 \x01(\tR\vsourceShard\x12.\n" +
	"\n" +
	"source_lsn\x18\x02 \x01(\v2\x0f.pgshard.v1.LsnR\tsourceLsn\x12<\n" +
	"\n" +
	"successors\x18\x03 \x03(\v2\x1c.pgshard.v1.JournalSuccessorR\n" +
	"successors\"\x89\x01\n" +
	"\x10JournalSuccessor\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\tR\x05shard\x121\n" +
	"\tkey_range\x18\x02 \x01(\v2\x14.pgshard.v1.KeyRangeR\bkeyRange\x12,\n" +
	"\tstart_lsn\x18\x03 \x01(\v2\x0f.pgshard.v1.LsnR\bstartLsn\"@\n" +
	"\x12CopyCompletedEvent\x12*\n" +
	"\x05table\x18\x01 \x01(\v2\x14.pgshard.v1.TableRefR\x05table\"\xb1\x04\n" +
	"\x06VEvent\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\tR\x05shard\x12;\n" +
	"\vcommit_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"commitTime\x12.\n" +
	"\x05begin\x18\x03 \x01(\v2\x16.pgshard.v1.BeginEventH\x00R\x05begin\x12.\n" +
	"\x05field\x18\x04 \x01(\v2\x16.pgshard.v1.FieldEventH\x00R\x05field\x12(\n" +
	"\x03row\x18\x05 \x01(\v2\x14.pgshard.v1.RowEventH\x00R\x03row\x121\n" +
	"\x06commit\x18\x06 \x01(\v2\x17.pgshard.v1.CommitEventH\x00R\x06commit\x12(\n" +
	"\x03ddl\x18\a \x01(\v2\x14.pgshard.v1.DdlEventH\x00R\x03ddl\x124\n" +
	"\ajournal\x18\b \x01(\v2\x18.pgshard.v1.JournalEventH\x00R\ajournal\x12)\n" +
	"\x05vgtid\x18\t \x01(\v2\x11.pgshard.v1.VGtidH\x00R\x05vgtid\x12:\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x1a.pgshard.v1.HeartbeatEventH\x00R\theartbeat\x12G\n" +
	"\x0ecopy_completed\x18\v \x01(\v2\x1e.pgshard.v1.CopyCompletedEventH\x00R\rcopyCompletedB\a\n" +
	"\x05event*X\n" +
	"\x05RowOp\x12\x16\n" +
	"\x12ROW_OP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rROW_OP_INSERT\x10\x01\x12\x11\n" +
	"\rROW_OP_UPDATE\x10\x02\x12\x11\n" +
	"\rROW_OP_DELETE\x10\x032S\n" +
	"\x0eVStreamService\x12A\n" +
	"\x06Stream\x12\x19.pgshard.v1.StreamRequest\x1a\x1a.pgshard.v1.StreamResponse0\x01BFZDgithub.com/andrew01234567890/pgshard2/operator/internal/pb/pgshardv1b\x06proto3"

var (
	file_pgshard_v1_vstream_proto_rawDescOnce sync.Once
	file_pgshard_v1_vstream_proto_rawDescData []byte
)

func file_pgshard_v1_vstream_proto_rawDescGZIP() []byte {
	file_pgshard_v1_vstream_proto_rawDescOnce.Do(func() {
		file_pgshard_v1_vstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pgshard_v1_vstream_proto_rawDesc), len(file_pgshard_v1_vstream_proto_rawDesc)))
	})
	return file_pgshard_v1_vstream_proto_rawDescData
}

var file_pgshard_v1_vstream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pgshard_v1_vstream_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pgshard_v1_vstream_proto_goTypes = []any{
	(RowOp)(0),                     // 0: pgshard.v1.RowOp
	(*VGtid)(nil),                  // 1: pgshard.v1.VGtid
	(*ShardGtid)(nil),              // 2: pgshard.v1.ShardGtid
	(*LatestStart)(nil),            // 3: pgshard.v1.LatestStart
	(*SnapshotAndFollowStart)(nil), // 4: pgshard.v1.SnapshotAndFollowStart
	(*StreamRequest)(nil),          // 5: pgshard.v1.StreamRequest
	(*StreamResponse)(nil),         // 6: pgshard.v1.StreamResponse
	(*Field)(nil),                  // 7: pgshard.v1.Field
	(*FieldEvent)(nil),             // 8: pgshard.v1.FieldEvent
	(*CellValue)(nil),              // 9: pgshard.v1.CellValue
	(*RowEvent)(nil),               // 10: pgshard.v1.RowEvent
	(*BeginEvent)(nil),             // 11: pgshard.v1.BeginEvent
	(*CommitEvent)(nil),            // 12: pgshard.v1.CommitEvent
	(*HeartbeatEvent)(nil),         // 13: pgshard.v1.HeartbeatEvent
	(*DdlEvent)(nil),               // 14: pgshard.v1.DdlEvent
	(*JournalEvent)(nil),           // 15: pgshard.v1.JournalEvent
	(*JournalSuccessor)(nil),       // 16: pgshard.v1.JournalSuccessor
	(*CopyCompletedEvent)(nil),     // 17: pgshard.v1.CopyCompletedEvent
	(*VEvent)(nil),                 // 18: pgshard.v1.VEvent
	(*Lsn)(nil),                    // 19: pgshard.v1.Lsn
	(*TableRef)(nil),               // 20: pgshard.v1.TableRef
	(*KeyRange)(nil),               // 21: pgshard.v1.KeyRange
	(*timestamppb.Timestamp)(nil),  // 22: google.protobuf.Timestamp
}
var file_pgshard_v1_vstream_proto_depIdxs = []int32{
	2,  // 0: pgshard.v1.VGtid.shard_gtids:type_name -> pgshard.v1.ShardGtid
	19, // 1: pgshard.v1.ShardGtid.lsn:type_name -> pgshard.v1.Lsn
	20, // 2: pgshard.v1.ShardGtid.tables_copied:type_name -> pgshard.v1.TableRef
	20, // 3: pgshard.v1.StreamRequest.tables:type_name -> pgshard.v1.TableRef
	1,  // 4: pgshard.v1.StreamRequest.position:type_name -> pgshard.v1.VGtid
	3,  // 5: pgshard.v1.StreamRequest.latest:type_name -> pgshard.v1.LatestStart
	4,  // 6: pgshard.v1.StreamRequest.snapshot_and_follow:type_name -> pgshard.v1.SnapshotAndFollowStart
	18, // 7: pgshard.v1.StreamResponse.event:type_name -> pgshard.v1.VEvent
	20, // 8: pgshard.v1.FieldEvent.table:type_name -> pgshard.v1.TableRef
	7,  // 9: pgshard.v1.FieldEvent.fields:type_name -> pgshard.v1.Field
	20, // 10: pgshard.v1.RowEvent.table:type_name -> pgshard.v1.TableRef
	0,  // 11: pgshard.v1.RowEvent.op:type_name -> pgshard.v1.RowOp
	9,  // 12: pgshard.v1.RowEvent.before:type_name -> pgshard.v1.CellValue
	9,  // 13: pgshard.v1.RowEvent.after:type_name -> pgshard.v1.CellValue
	19, // 14: pgshard.v1.BeginEvent.lsn:type_name -> pgshard.v1.Lsn
	19, // 15: pgshard.v1.CommitEvent.lsn:type_name -> pgshard.v1.Lsn
	19, // 16: pgshard.v1.JournalEvent.source_lsn:type_name -> pgshard.v1.Lsn
	16, // 17: pgshard.v1.JournalEvent.successors:type_name -> pgshard.v1.JournalSuccessor
	21, // 18: pgshard.v1.JournalSuccessor.key_range:type_name -> pgshard.v1.KeyRange
	19, // 19: pgshard.v1.JournalSuccessor.start_lsn:type_name -> pgshard.v1.Lsn
	20, // 20: pgshard.v1.CopyCompletedEvent.table:type_name -> pgshard.v1.TableRef
	22, // 21: pgshard.v1.VEvent.commit_time:type_name -> google.protobuf.Timestamp
	11, // 22: pgshard.v1.VEvent.begin:type_name -> pgshard.v1.BeginEvent
	8,  // 23: pgshard.v1.VEvent.field:type_name -> pgshard.v1.FieldEvent
	10, // 24: pgshard.v1.VEvent.row:type_name -> pgshard.v1.RowEvent
	12, // 25: pgshard.v1.VEvent.commit:type_name -> pgshard.v1.CommitEvent
	14, // 26: pgshard.v1.VEvent.ddl:type_name -> pgshard.v1.DdlEvent
	15, // 27: pgshard.v1.VEvent.journal:type_name -> pgshard.v1.JournalEvent
	1,  // 28: pgshard.v1.VEvent.vgtid:type_name -> pgshard.v1.VGtid
	13, // 29: pgshard.v1.VEvent.heartbeat:type_name -> pgshard.v1.HeartbeatEvent
	17, // 30: pgshard.v1.VEvent.copy_completed:type_name -> pgshard.v1.CopyCompletedEvent
	5,  // 31: pgshard.v1.VStreamService.Stream:input_type -> pgshard.v1.StreamRequest
	6,  // 32: pgshard.v1.VStreamService.Stream:output_type -> pgshard.v1.StreamResponse
	32, // [32:33] is the sub-list for method output_type
	31, // [31:32] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_pgshard_v1_vstream_proto_init() }
func file_pgshard_v1_vstream_proto_init() {
	if File_pgshard_v1_vstream_proto != nil {
		return
	}
	file_pgshard_v1_common_proto_init()
	file_pgshard_v1_vstream_proto_msgTypes[4].OneofWrappers = []any{
		(*StreamRequest_Position)(nil),
		(*StreamRequest_Latest)(nil),
		(*StreamRequest_SnapshotAndFollow)(nil),
	}
	file_pgshard_v1_vstream_proto_msgTypes[17].OneofWrappers = []any{
		(*VEvent_Begin)(nil),
		(*VEvent_Field)(nil),
		(*VEvent_Row)(nil),
		(*VEvent_Commit)(nil),
		(*VEvent_Ddl)(nil),
		(*VEvent_Journal)(nil),
		(*VEvent_Vgtid)(nil),
		(*VEvent_Heartbeat)(nil),
		(*VEvent_CopyCompleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgshard_v1_vstream_proto_rawDesc), len(file_pgshard_v1_vstream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pgshard_v1_vstream_proto_goTypes,
		DependencyIndexes: file_pgshard_v1_vstream_proto_depIdxs,
		EnumInfos:         file_pgshard_v1_vstream_proto_enumTypes,
		MessageInfos:      file_pgshard_v1_vstream_proto_msgTypes,
	}.Build()
	File_pgshard_v1_vstream_proto = out.File
	file_pgshard_v1_vstream_proto_goTypes = nil
	file_pgshard_v1_vstream_proto_depIdxs = nil
}
