// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pgshard/v1/vstream.proto

package pgshardv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VStreamService_Stream_FullMethodName = "/pgshard.v1.VStreamService/Stream"
)

// VStreamServiceClient is the client API for VStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Served by routers: the merged, reshard-transparent cross-shard stream.
type VStreamServiceClient interface {
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
}

type vStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVStreamServiceClient(cc grpc.ClientConnInterface) VStreamServiceClient {
	return &vStreamServiceClient{cc}
}

func (c *vStreamServiceClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VStreamService_ServiceDesc.Streams[0], VStreamService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VStreamService_StreamClient = grpc.ServerStreamingClient[StreamResponse]

// VStreamServiceServer is the server API for VStreamService service.
// All implementations must embed UnimplementedVStreamServiceServer
// for forward compatibility.
//
// Served by routers: the merged, reshard-transparent cross-shard stream.
type VStreamServiceServer interface {
	Stream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error
	mustEmbedUnimplementedVStreamServiceServer()
}

// UnimplementedVStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVStreamServiceServer struct{}

func (UnimplementedVStreamServiceServer) Stream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedVStreamServiceServer) mustEmbedUnimplementedVStreamServiceServer() {}
func (UnimplementedVStreamServiceServer) testEmbeddedByValue()                        {}

// UnsafeVStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VStreamServiceServer will
// result in compilation errors.
type UnsafeVStreamServiceServer interface {
	mustEmbedUnimplementedVStreamServiceServer()
}

func RegisterVStreamServiceServer(s grpc.ServiceRegistrar, srv VStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedVStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VStreamService_ServiceDesc, srv)
}

func _VStreamService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VStreamServiceServer).Stream(m, &grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VStreamService_StreamServer = grpc.ServerStreamingServer[StreamResponse]

// VStreamService_ServiceDesc is the grpc.ServiceDesc for VStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pgshard.v1.VStreamService",
	HandlerType: (*VStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _VStreamService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pgshard/v1/vstream.proto",
}
