// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pgshard/v1/workflow.proto

package pgshardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowKind int32

const (
	WorkflowKind_WORKFLOW_KIND_UNSPECIFIED WorkflowKind = 0
	// Keyrange-filtered copy + streaming apply for resharding (forward or reverse).
	WorkflowKind_WORKFLOW_KIND_RESHARD WorkflowKind = 1
	// Same-instance shadow-table backfill for online DDL.
	WorkflowKind_WORKFLOW_KIND_DDL_SHADOW WorkflowKind = 2
)

// Enum value maps for WorkflowKind.
var (
	WorkflowKind_name = map[int32]string{
		0: "WORKFLOW_KIND_UNSPECIFIED",
		1: "WORKFLOW_KIND_RESHARD",
		2: "WORKFLOW_KIND_DDL_SHADOW",
	}
	WorkflowKind_value = map[string]int32{
		"WORKFLOW_KIND_UNSPECIFIED": 0,
		"WORKFLOW_KIND_RESHARD":     1,
		"WORKFLOW_KIND_DDL_SHADOW":  2,
	}
)

func (x WorkflowKind) Enum() *WorkflowKind {
	p := new(WorkflowKind)
	*p = x
	return p
}

func (x WorkflowKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_workflow_proto_enumTypes[0].Descriptor()
}

func (WorkflowKind) Type() protoreflect.EnumType {
	return &file_pgshard_v1_workflow_proto_enumTypes[0]
}

func (x WorkflowKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowKind.Descriptor instead.
func (WorkflowKind) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_workflow_proto_rawDescGZIP(), []int{0}
}

type WorkflowPhase int32

const (
	WorkflowPhase_WORKFLOW_PHASE_UNSPECIFIED WorkflowPhase = 0
	WorkflowPhase_WORKFLOW_PHASE_INIT        WorkflowPhase = 1
	WorkflowPhase_WORKFLOW_PHASE_COPY        WorkflowPhase = 2
	WorkflowPhase_WORKFLOW_PHASE_STREAMING   WorkflowPhase = 3
	WorkflowPhase_WORKFLOW_PHASE_STOPPED     WorkflowPhase = 4
	WorkflowPhase_WORKFLOW_PHASE_ERROR       WorkflowPhase = 5
)

// Enum value maps for WorkflowPhase.
var (
	WorkflowPhase_name = map[int32]string{
		0: "WORKFLOW_PHASE_UNSPECIFIED",
		1: "WORKFLOW_PHASE_INIT",
		2: "WORKFLOW_PHASE_COPY",
		3: "WORKFLOW_PHASE_STREAMING",
		4: "WORKFLOW_PHASE_STOPPED",
		5: "WORKFLOW_PHASE_ERROR",
	}
	WorkflowPhase_value = map[string]int32{
		"WORKFLOW_PHASE_UNSPECIFIED": 0,
		"WORKFLOW_PHASE_INIT":        1,
		"WORKFLOW_PHASE_COPY":        2,
		"WORKFLOW_PHASE_STREAMING":   3,
		"WORKFLOW_PHASE_STOPPED":     4,
		"WORKFLOW_PHASE_ERROR":       5,
	}
)

func (x WorkflowPhase) Enum() *WorkflowPhase {
	p := new(WorkflowPhase)
	*p = x
	return p
}

func (x WorkflowPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_pgshard_v1_workflow_proto_enumTypes[1].Descriptor()
}

func (WorkflowPhase) Type() protoreflect.EnumType {
	return &file_pgshard_v1_workflow_proto_enumTypes[1]
}

func (x WorkflowPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowPhase.Descriptor instead.
func (WorkflowPhase) EnumDescriptor() ([]byte, []int) {
	return file_pgshard_v1_workflow_proto_rawDescGZIP(), []int{1}
}

type TableMapping struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source *TableRef              `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target *TableRef              `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Source column -> target column. Empty means identity mapping. Non-empty
	// mappings are not implemented in M1 (the runner rejects them).
	ColumnMap map[string]string `protobuf:"bytes,3,rep,name=column_map,json=columnMap,proto3" json:"column_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The table's shard-key column and its declared type (wire values int |
	// text | uuid | bytea, matching the router's ShardKeyType). Required when
	// the workflow filter is a key range: both the snapshot copy and the
	// stream filter hash this column to decide keep-or-skip, and hashing under
	// the wrong type would route rows to the wrong shard.
	ShardKeyColumn string `protobuf:"bytes,4,opt,name=shard_key_column,json=shardKeyColumn,proto3" json:"shard_key_column,omitempty"`
	ShardKeyType   string `protobuf:"bytes,5,opt,name=shard_key_type,json=shardKeyType,proto3" json:"shard_key_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TableMapping) Reset() {
	*x = TableMapping{}
	mi := &file_pgshard_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMapping) ProtoMessage() {}

func (x *TableMapping) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMapping.ProtoReflect.Descriptor instead.
func (*TableMapping) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *TableMapping) GetSource() *TableRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TableMapping) GetTarget() *TableRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TableMapping) GetColumnMap() map[string]string {
	if x != nil {
		return x.ColumnMap
	}
	return nil
}

func (x *TableMapping) GetShardKeyColumn() string {
	if x != nil {
		return x.ShardKeyColumn
	}
	return ""
}

func (x *TableMapping) GetShardKeyType() string {
	if x != nil {
		return x.ShardKeyType
	}
	return ""
}

type KeyRangeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *KeyRange              `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	HashFunction  string                 `protobuf:"bytes,2,opt,name=hash_function,json=hashFunction,proto3" json:"hash_function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRangeFilter) Reset() {
	*x = KeyRangeFilter{}
	mi := &file_pgshard_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRangeFilter) ProtoMessage() {}

func (x *KeyRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRangeFilter.ProtoReflect.Descriptor instead.
func (*KeyRangeFilter) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *KeyRangeFilter) GetRange() *KeyRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *KeyRangeFilter) GetHashFunction() string {
	if x != nil {
		return x.HashFunction
	}
	return ""
}

type RowFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*RowFilter_All
	//	*RowFilter_KeyRange
	Filter        isRowFilter_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowFilter) Reset() {
	*x = RowFilter{}
	mi := &file_pgshard_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowFilter) ProtoMessage() {}

func (x *RowFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowFilter.ProtoReflect.Descriptor instead.
func (*RowFilter) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *RowFilter) GetFilter() isRowFilter_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *RowFilter) GetAll() bool {
	if x != nil {
		if x, ok := x.Filter.(*RowFilter_All); ok {
			return x.All
		}
	}
	return false
}

func (x *RowFilter) GetKeyRange() *KeyRangeFilter {
	if x != nil {
		if x, ok := x.Filter.(*RowFilter_KeyRange); ok {
			return x.KeyRange
		}
	}
	return nil
}

type isRowFilter_Filter interface {
	isRowFilter_Filter()
}

type RowFilter_All struct {
	All bool `protobuf:"varint,1,opt,name=all,proto3,oneof"`
}

type RowFilter_KeyRange struct {
	KeyRange *KeyRangeFilter `protobuf:"bytes,2,opt,name=key_range,json=keyRange,proto3,oneof"`
}

func (*RowFilter_All) isRowFilter_Filter() {}

func (*RowFilter_KeyRange) isRowFilter_Filter() {}

// A replication worker runs on the TARGET agent and pulls from the source.
// Source credentials come from the target agent's own replication-user
// configuration (not the wire) until agent<->agent auth lands with mTLS.
type WorkflowSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind           WorkflowKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=pgshard.v1.WorkflowKind" json:"kind,omitempty"`
	SourceShard    string                 `protobuf:"bytes,3,opt,name=source_shard,json=sourceShard,proto3" json:"source_shard,omitempty"`
	SourcePrimary  *PgEndpoint            `protobuf:"bytes,4,opt,name=source_primary,json=sourcePrimary,proto3" json:"source_primary,omitempty"`
	SourceStandbys []*PgEndpoint          `protobuf:"bytes,5,rep,name=source_standbys,json=sourceStandbys,proto3" json:"source_standbys,omitempty"`
	SourcePolicy   SourcePolicy           `protobuf:"varint,6,opt,name=source_policy,json=sourcePolicy,proto3,enum=pgshard.v1.SourcePolicy" json:"source_policy,omitempty"`
	Slot           string                 `protobuf:"bytes,7,opt,name=slot,proto3" json:"slot,omitempty"`
	Publication    string                 `protobuf:"bytes,8,opt,name=publication,proto3" json:"publication,omitempty"`
	Tables         []*TableMapping        `protobuf:"bytes,9,rep,name=tables,proto3" json:"tables,omitempty"`
	Filter         *RowFilter             `protobuf:"bytes,10,opt,name=filter,proto3" json:"filter,omitempty"`
	// The local database the worker seeds and applies into (the placed shard's
	// database on this agent's node). Required.
	TargetDatabase string `protobuf:"bytes,11,opt,name=target_database,json=targetDatabase,proto3" json:"target_database,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkflowSpec) Reset() {
	*x = WorkflowSpec{}
	mi := &file_pgshard_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSpec) ProtoMessage() {}

func (x *WorkflowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSpec.ProtoReflect.Descriptor instead.
func (*WorkflowSpec) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowSpec) GetKind() WorkflowKind {
	if x != nil {
		return x.Kind
	}
	return WorkflowKind_WORKFLOW_KIND_UNSPECIFIED
}

func (x *WorkflowSpec) GetSourceShard() string {
	if x != nil {
		return x.SourceShard
	}
	return ""
}

func (x *WorkflowSpec) GetSourcePrimary() *PgEndpoint {
	if x != nil {
		return x.SourcePrimary
	}
	return nil
}

func (x *WorkflowSpec) GetSourceStandbys() []*PgEndpoint {
	if x != nil {
		return x.SourceStandbys
	}
	return nil
}

func (x *WorkflowSpec) GetSourcePolicy() SourcePolicy {
	if x != nil {
		return x.SourcePolicy
	}
	return SourcePolicy_SOURCE_POLICY_UNSPECIFIED
}

func (x *WorkflowSpec) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *WorkflowSpec) GetPublication() string {
	if x != nil {
		return x.Publication
	}
	return ""
}

func (x *WorkflowSpec) GetTables() []*TableMapping {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *WorkflowSpec) GetFilter() *RowFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *WorkflowSpec) GetTargetDatabase() string {
	if x != nil {
		return x.TargetDatabase
	}
	return ""
}

type CopyProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TablesTotal   uint32                 `protobuf:"varint,1,opt,name=tables_total,json=tablesTotal,proto3" json:"tables_total,omitempty"`
	TablesDone    uint32                 `protobuf:"varint,2,opt,name=tables_done,json=tablesDone,proto3" json:"tables_done,omitempty"`
	RowsCopied    uint64                 `protobuf:"varint,3,opt,name=rows_copied,json=rowsCopied,proto3" json:"rows_copied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyProgress) Reset() {
	*x = CopyProgress{}
	mi := &file_pgshard_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyProgress) ProtoMessage() {}

func (x *CopyProgress) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyProgress.ProtoReflect.Descriptor instead.
func (*CopyProgress) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *CopyProgress) GetTablesTotal() uint32 {
	if x != nil {
		return x.TablesTotal
	}
	return 0
}

func (x *CopyProgress) GetTablesDone() uint32 {
	if x != nil {
		return x.TablesDone
	}
	return 0
}

func (x *CopyProgress) GetRowsCopied() uint64 {
	if x != nil {
		return x.RowsCopied
	}
	return 0
}

type WorkflowStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase         WorkflowPhase          `protobuf:"varint,2,opt,name=phase,proto3,enum=pgshard.v1.WorkflowPhase" json:"phase,omitempty"`
	Copy          *CopyProgress          `protobuf:"bytes,3,opt,name=copy,proto3" json:"copy,omitempty"`
	AppliedLsn    *Lsn                   `protobuf:"bytes,4,opt,name=applied_lsn,json=appliedLsn,proto3" json:"applied_lsn,omitempty"`
	LagBytes      uint64                 `protobuf:"varint,5,opt,name=lag_bytes,json=lagBytes,proto3" json:"lag_bytes,omitempty"`
	LagSeconds    float64                `protobuf:"fixed64,6,opt,name=lag_seconds,json=lagSeconds,proto3" json:"lag_seconds,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStatus) Reset() {
	*x = WorkflowStatus{}
	mi := &file_pgshard_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatus) ProtoMessage() {}

func (x *WorkflowStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pgshard_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatus.ProtoReflect.Descriptor instead.
func (*WorkflowStatus) Descriptor() ([]byte, []int) {
	return file_pgshard_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowStatus) GetPhase() WorkflowPhase {
	if x != nil {
		return x.Phase
	}
	return WorkflowPhase_WORKFLOW_PHASE_UNSPECIFIED
}

func (x *WorkflowStatus) GetCopy() *CopyProgress {
	if x != nil {
		return x.Copy
	}
	return nil
}

func (x *WorkflowStatus) GetAppliedLsn() *Lsn {
	if x != nil {
		return x.AppliedLsn
	}
	return nil
}

func (x *WorkflowStatus) GetLagBytes() uint64 {
	if x != nil {
		return x.LagBytes
	}
	return 0
}

func (x *WorkflowStatus) GetLagSeconds() float64 {
	if x != nil {
		return x.LagSeconds
	}
	return 0
}

func (x *WorkflowStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pgshard_v1_workflow_proto protoreflect.FileDescriptor

const file_pgshard_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x19pgshard/v1/workflow.proto\x12\n" +
	"pgshard.v1\x1a\x17pgshard/v1/common.proto\"\xc0\x02\n" +
	"\fTableMapping\x12,\n" +
	"\x06source\x18\x01 \x01(\v2\x14.pgshard.v1.TableRefR\x06source\x12,\n" +
	"\x06target\x18\x02 \x01(\v2\x14.pgshard.v1.TableRefR\x06target\x12F\n" +
	"\n" +
	"column_map\x18\x03 \x03(\v2'.pgshard.v1.TableMapping.ColumnMapEntryR\tcolumnMap\x12(\n" +
	"\x10shard_key_column\x18\x04 \x01(\tR\x0eshardKeyColumn\x12$\n" +
	"\x0eshard_key_type\x18\x05 \x01(\tR\fshardKeyType\x1a<\n" +
	"\x0eColumnMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x0eKeyRangeFilter\x12*\n" +
	"\x05range\x18\x01 \x01(\v2\x14.pgshard.v1.KeyRangeR\x05range\x12#\n" +
	"\rhash_function\x18\x02 \x01(\tR\fhashFunction\"d\n" +
	"\tRowFilter\x12\x12\n" +
	"\x03all\x18\x01 \x01(\bH\x00R\x03all\x129\n" +
	"\tkey_range\x18\x02 \x01(\v2\x1a.pgshard.v1.KeyRangeFilterH\x00R\bkeyRangeB\b\n" +
	"\x06filter\"\xee\x03\n" +
	"\fWorkflowSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x18.pgshard.v1.WorkflowKindR\x04kind\x12!\n" +
	"\fsource_shard\x18\x03 \x01(\tR\vsourceShard\x12=\n" +
	"\x0esource_primary\x18\x04 \x01(\v2\x16.pgshard.v1.PgEndpointR\rsourcePrimary\x12?\n" +
	"\x0fsource_standbys\x18\x05 \x03(\v2\x16.pgshard.v1.PgEndpointR\x0esourceStandbys\x12=\n" +
	"\rsource_policy\x18\x06 \x01(\x0e2\x18.pgshard.v1.SourcePolicyR\fsourcePolicy\x12\x12\n" +
	"\x04slot\x18\a \x01(\tR\x04slot\x12 \n" +
	"\vpublication\x18\b \x01(\tR\vpublication\x120\n" +
	"\x06tables\x18\t \x03(\v2\x18.pgshard.v1.TableMappingR\x06tables\x12-\n" +
	"\x06filter\x18\n" +
	" \x01(\v2\x15.pgshard.v1.RowFilterR\x06filter\x12'\n" +
	"\x0ftarget_database\x18\v \x01(\tR\x0etargetDatabase\"s\n" +
	"\fCopyProgress\x12!\n" +
	"\ftables_total\x18\x01 \x01(\rR\vtablesTotal\x12\x1f\n" +
	"\vtables_done\x18\x02 \x01(\rR\n" +
	"tablesDone\x12\x1f\n" +
	"\vrows_copied\x18\x03 \x01(\x04R\n" +
	"rowsCopied\"\x85\x02\n" +
	"\x0eWorkflowStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x19.pgshard.v1.WorkflowPhaseR\x05phase\x12,\n" +
	"\x04copy\x18\x03 \x01(\v2\x18.pgshard.v1.CopyProgressR\x04copy\x120\n" +
	"\vapplied_lsn\x18\x04 \x01(\v2\x0f.pgshard.v1.LsnR\n" +
	"appliedLsn\x12\x1b\n" +
	"\tlag_bytes\x18\x05 \x01(\x04R\blagBytes\x12\x1f\n" +
	"\vlag_seconds\x18\x06 \x01(\x01R\n" +
	"lagSeconds\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error*f\n" +
	"\fWorkflowKind\x12\x1d\n" +
	"\x19WORKFLOW_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WORKFLOW_KIND_RESHARD\x10\x01\x12\x1c\n" +
	"\x18WORKFLOW_KIND_DDL_SHADOW\x10\x02*\xb5\x01\n" +
	"\rWorkflowPhase\x12\x1e\n" +
	"\x1aWORKFLOW_PHASE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13WORKFLOW_PHASE_INIT\x10\x01\x12\x17\n" +
	"\x13WORKFLOW_PHASE_COPY\x10\x02\x12\x1c\n" +
	"\x18WORKFLOW_PHASE_STREAMING\x10\x03\x12\x1a\n" +
	"\x16WORKFLOW_PHASE_STOPPED\x10\x04\x12\x18\n" +
	"\x14WORKFLOW_PHASE_ERROR\x10\x05BFZDgithub.com/andrew01234567890/pgshard2/operator/internal/pb/pgshardv1b\x06proto3"

var (
	file_pgshard_v1_workflow_proto_rawDescOnce sync.Once
	file_pgshard_v1_workflow_proto_rawDescData []byte
)

func file_pgshard_v1_workflow_proto_rawDescGZIP() []byte {
	file_pgshard_v1_workflow_proto_rawDescOnce.Do(func() {
		file_pgshard_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pgshard_v1_workflow_proto_rawDesc), len(file_pgshard_v1_workflow_proto_rawDesc)))
	})
	return file_pgshard_v1_workflow_proto_rawDescData
}

var file_pgshard_v1_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pgshard_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pgshard_v1_workflow_proto_goTypes = []any{
	(WorkflowKind)(0),      // 0: pgshard.v1.WorkflowKind
	(WorkflowPhase)(0),     // 1: pgshard.v1.WorkflowPhase
	(*TableMapping)(nil),   // 2: pgshard.v1.TableMapping
	(*KeyRangeFilter)(nil), // 3: pgshard.v1.KeyRangeFilter
	(*RowFilter)(nil),      // 4: pgshard.v1.RowFilter
	(*WorkflowSpec)(nil),   // 5: pgshard.v1.WorkflowSpec
	(*CopyProgress)(nil),   // 6: pgshard.v1.CopyProgress
	(*WorkflowStatus)(nil), // 7: pgshard.v1.WorkflowStatus
	nil,                    // 8: pgshard.v1.TableMapping.ColumnMapEntry
	(*TableRef)(nil),       // 9: pgshard.v1.TableRef
	(*KeyRange)(nil),       // 10: pgshard.v1.KeyRange
	(*PgEndpoint)(nil),     // 11: pgshard.v1.PgEndpoint
	(SourcePolicy)(0),      // 12: pgshard.v1.SourcePolicy
	(*Lsn)(nil),            // 13: pgshard.v1.Lsn
}
var file_pgshard_v1_workflow_proto_depIdxs = []int32{
	9,  // 0: pgshard.v1.TableMapping.source:type_name -> pgshard.v1.TableRef
	9,  // 1: pgshard.v1.TableMapping.target:type_name -> pgshard.v1.TableRef
	8,  // 2: pgshard.v1.TableMapping.column_map:type_name -> pgshard.v1.TableMapping.ColumnMapEntry
	10, // 3: pgshard.v1.KeyRangeFilter.range:type_name -> pgshard.v1.KeyRange
	3,  // 4: pgshard.v1.RowFilter.key_range:type_name -> pgshard.v1.KeyRangeFilter
	0,  // 5: pgshard.v1.WorkflowSpec.kind:type_name -> pgshard.v1.WorkflowKind
	11, // 6: pgshard.v1.WorkflowSpec.source_primary:type_name -> pgshard.v1.PgEndpoint
	11, // 7: pgshard.v1.WorkflowSpec.source_standbys:type_name -> pgshard.v1.PgEndpoint
	12, // 8: pgshard.v1.WorkflowSpec.source_policy:type_name -> pgshard.v1.SourcePolicy
	2,  // 9: pgshard.v1.WorkflowSpec.tables:type_name -> pgshard.v1.TableMapping
	4,  // 10: pgshard.v1.WorkflowSpec.filter:type_name -> pgshard.v1.RowFilter
	1,  // 11: pgshard.v1.WorkflowStatus.phase:type_name -> pgshard.v1.WorkflowPhase
	6,  // 12: pgshard.v1.WorkflowStatus.copy:type_name -> pgshard.v1.CopyProgress
	13, // 13: pgshard.v1.WorkflowStatus.applied_lsn:type_name -> pgshard.v1.Lsn
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pgshard_v1_workflow_proto_init() }
func file_pgshard_v1_workflow_proto_init() {
	if File_pgshard_v1_workflow_proto != nil {
		return
	}
	file_pgshard_v1_common_proto_init()
	file_pgshard_v1_workflow_proto_msgTypes[2].OneofWrappers = []any{
		(*RowFilter_All)(nil),
		(*RowFilter_KeyRange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgshard_v1_workflow_proto_rawDesc), len(file_pgshard_v1_workflow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pgshard_v1_workflow_proto_goTypes,
		DependencyIndexes: file_pgshard_v1_workflow_proto_depIdxs,
		EnumInfos:         file_pgshard_v1_workflow_proto_enumTypes,
		MessageInfos:      file_pgshard_v1_workflow_proto_msgTypes,
	}.Build()
	File_pgshard_v1_workflow_proto = out.File
	file_pgshard_v1_workflow_proto_goTypes = nil
	file_pgshard_v1_workflow_proto_depIdxs = nil
}
