//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepoSpec) DeepCopyInto(out *BackupRepoSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepoSpec.
func (in *BackupRepoSpec) DeepCopy() *BackupRepoSpec {
	if in == nil {
		return nil
	}
	out := new(BackupRepoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSchedulesSpec) DeepCopyInto(out *BackupSchedulesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSchedulesSpec.
func (in *BackupSchedulesSpec) DeepCopy() *BackupSchedulesSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSchedulesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	out.Repo = in.Repo
	out.Schedules = in.Schedules
	in.Barrier.DeepCopyInto(&out.Barrier)
	out.Retention = in.Retention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSpec.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarrierRecord) DeepCopyInto(out *BarrierRecord) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarrierRecord.
func (in *BarrierRecord) DeepCopy() *BarrierRecord {
	if in == nil {
		return nil
	}
	out := new(BarrierRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarrierSpec) DeepCopyInto(out *BarrierSpec) {
	*out = *in
	out.Interval = in.Interval
	out.GateDeadline = in.GateDeadline
	if in.ForceWalSwitch != nil {
		in, out := &in.ForceWalSwitch, &out.ForceWalSwitch
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarrierSpec.
func (in *BarrierSpec) DeepCopy() *BarrierSpec {
	if in == nil {
		return nil
	}
	out := new(BarrierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBackupStatus) DeepCopyInto(out *ClusterBackupStatus) {
	*out = *in
	if in.LastBarrierTime != nil {
		in, out := &in.LastBarrierTime, &out.LastBarrierTime
		*out = (*in).DeepCopy()
	}
	if in.LastFullBackupTime != nil {
		in, out := &in.LastFullBackupTime, &out.LastFullBackupTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBackupStatus.
func (in *ClusterBackupStatus) DeepCopy() *ClusterBackupStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GateMatch) DeepCopyInto(out *GateMatch) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeyRanges != nil {
		in, out := &in.KeyRanges, &out.KeyRanges
		*out = make([]KeyRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GateMatch.
func (in *GateMatch) DeepCopy() *GateMatch {
	if in == nil {
		return nil
	}
	out := new(GateMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceState) DeepCopyInto(out *InstanceState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceState.
func (in *InstanceState) DeepCopy() *InstanceState {
	if in == nil {
		return nil
	}
	out := new(InstanceState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyRange) DeepCopyInto(out *KeyRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyRange.
func (in *KeyRange) DeepCopy() *KeyRange {
	if in == nil {
		return nil
	}
	out := new(KeyRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardCluster) DeepCopyInto(out *PgShardCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardCluster.
func (in *PgShardCluster) DeepCopy() *PgShardCluster {
	if in == nil {
		return nil
	}
	out := new(PgShardCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardClusterList) DeepCopyInto(out *PgShardClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardClusterList.
func (in *PgShardClusterList) DeepCopy() *PgShardClusterList {
	if in == nil {
		return nil
	}
	out := new(PgShardClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardClusterSpec) DeepCopyInto(out *PgShardClusterSpec) {
	*out = *in
	in.Postgres.DeepCopyInto(&out.Postgres)
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(SizeSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Shards = in.Shards
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PlacementSpec)
		**out = **in
	}
	if in.Router != nil {
		in, out := &in.Router, &out.Router
		*out = new(RouterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(SystemSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardClusterSpec.
func (in *PgShardClusterSpec) DeepCopy() *PgShardClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardClusterStatus) DeepCopyInto(out *PgShardClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Shards = in.Shards
	out.Routers = in.Routers
	in.Backup.DeepCopyInto(&out.Backup)
	if in.RestoredFrom != nil {
		in, out := &in.RestoredFrom, &out.RestoredFrom
		*out = new(RestoredFrom)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardClusterStatus.
func (in *PgShardClusterStatus) DeepCopy() *PgShardClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardNode) DeepCopyInto(out *PgShardNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardNode.
func (in *PgShardNode) DeepCopy() *PgShardNode {
	if in == nil {
		return nil
	}
	out := new(PgShardNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardNodeList) DeepCopyInto(out *PgShardNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardNodeList.
func (in *PgShardNodeList) DeepCopy() *PgShardNodeList {
	if in == nil {
		return nil
	}
	out := new(PgShardNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardNodeSpec) DeepCopyInto(out *PgShardNodeSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardNodeSpec.
func (in *PgShardNodeSpec) DeepCopy() *PgShardNodeSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardNodeStatus) DeepCopyInto(out *PgShardNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetPrimaryTimestamp != nil {
		in, out := &in.TargetPrimaryTimestamp, &out.TargetPrimaryTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]InstanceState, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardNodeStatus.
func (in *PgShardNodeStatus) DeepCopy() *PgShardNodeStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardReshard) DeepCopyInto(out *PgShardReshard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardReshard.
func (in *PgShardReshard) DeepCopy() *PgShardReshard {
	if in == nil {
		return nil
	}
	out := new(PgShardReshard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardReshard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardReshardList) DeepCopyInto(out *PgShardReshardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardReshard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardReshardList.
func (in *PgShardReshardList) DeepCopy() *PgShardReshardList {
	if in == nil {
		return nil
	}
	out := new(PgShardReshardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardReshardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardReshardSpec) DeepCopyInto(out *PgShardReshardSpec) {
	*out = *in
	if in.TargetRanges != nil {
		in, out := &in.TargetRanges, &out.TargetRanges
		*out = make([]KeyRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardReshardSpec.
func (in *PgShardReshardSpec) DeepCopy() *PgShardReshardSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardReshardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardReshardStatus) DeepCopyInto(out *PgShardReshardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetShards != nil {
		in, out := &in.TargetShards, &out.TargetShards
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SeedTables != nil {
		in, out := &in.SeedTables, &out.SeedTables
		*out = make([]ReshardSeedTable, len(*in))
		copy(*out, *in)
	}
	if in.CutoverGateDeadline != nil {
		in, out := &in.CutoverGateDeadline, &out.CutoverGateDeadline
		*out = (*in).DeepCopy()
	}
	if in.CutoverGateObservedAt != nil {
		in, out := &in.CutoverGateObservedAt, &out.CutoverGateObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardReshardStatus.
func (in *PgShardReshardStatus) DeepCopy() *PgShardReshardStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardReshardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardRouting) DeepCopyInto(out *PgShardRouting) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardRouting.
func (in *PgShardRouting) DeepCopy() *PgShardRouting {
	if in == nil {
		return nil
	}
	out := new(PgShardRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardRouting) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardRoutingList) DeepCopyInto(out *PgShardRoutingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardRouting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardRoutingList.
func (in *PgShardRoutingList) DeepCopy() *PgShardRoutingList {
	if in == nil {
		return nil
	}
	out := new(PgShardRoutingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardRoutingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardRoutingSpec) DeepCopyInto(out *PgShardRoutingSpec) {
	*out = *in
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]RoutingShard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]RoutingTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gates != nil {
		in, out := &in.Gates, &out.Gates
		*out = make([]RoutingGate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SequenceEndpoint != nil {
		in, out := &in.SequenceEndpoint, &out.SequenceEndpoint
		*out = new(RoutingEndpoint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardRoutingSpec.
func (in *PgShardRoutingSpec) DeepCopy() *PgShardRoutingSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardRoutingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardRoutingStatus) DeepCopyInto(out *PgShardRoutingStatus) {
	*out = *in
	if in.CompiledAt != nil {
		in, out := &in.CompiledAt, &out.CompiledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardRoutingStatus.
func (in *PgShardRoutingStatus) DeepCopy() *PgShardRoutingStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardRoutingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardShard) DeepCopyInto(out *PgShardShard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardShard.
func (in *PgShardShard) DeepCopy() *PgShardShard {
	if in == nil {
		return nil
	}
	out := new(PgShardShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardShard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardShardList) DeepCopyInto(out *PgShardShardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardShard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardShardList.
func (in *PgShardShardList) DeepCopy() *PgShardShardList {
	if in == nil {
		return nil
	}
	out := new(PgShardShardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardShardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardShardSpec) DeepCopyInto(out *PgShardShardSpec) {
	*out = *in
	out.KeyRange = in.KeyRange
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ReplicationLinks != nil {
		in, out := &in.ReplicationLinks, &out.ReplicationLinks
		*out = make([]ReplicationLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardShardSpec.
func (in *PgShardShardSpec) DeepCopy() *PgShardShardSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardShardStatus) DeepCopyInto(out *PgShardShardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetPrimaryTimestamp != nil {
		in, out := &in.TargetPrimaryTimestamp, &out.TargetPrimaryTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]InstanceState, len(*in))
		copy(*out, *in)
	}
	if in.LastBarrier != nil {
		in, out := &in.LastBarrier, &out.LastBarrier
		*out = new(BarrierRecord)
		(*in).DeepCopyInto(*out)
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]ReplicationLinkStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardShardStatus.
func (in *PgShardShardStatus) DeepCopy() *PgShardShardStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardShardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardTableConfig) DeepCopyInto(out *PgShardTableConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardTableConfig.
func (in *PgShardTableConfig) DeepCopy() *PgShardTableConfig {
	if in == nil {
		return nil
	}
	out := new(PgShardTableConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardTableConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardTableConfigList) DeepCopyInto(out *PgShardTableConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgShardTableConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardTableConfigList.
func (in *PgShardTableConfigList) DeepCopy() *PgShardTableConfigList {
	if in == nil {
		return nil
	}
	out := new(PgShardTableConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgShardTableConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardTableConfigSpec) DeepCopyInto(out *PgShardTableConfigSpec) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]TableEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sequences != nil {
		in, out := &in.Sequences, &out.Sequences
		*out = make([]SequenceEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardTableConfigSpec.
func (in *PgShardTableConfigSpec) DeepCopy() *PgShardTableConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PgShardTableConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgShardTableConfigStatus) DeepCopyInto(out *PgShardTableConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgShardTableConfigStatus.
func (in *PgShardTableConfigStatus) DeepCopy() *PgShardTableConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PgShardTableConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementSpec) DeepCopyInto(out *PlacementSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementSpec.
func (in *PlacementSpec) DeepCopy() *PlacementSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresSpec) DeepCopyInto(out *PostgresSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresSpec.
func (in *PostgresSpec) DeepCopy() *PostgresSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationLink) DeepCopyInto(out *ReplicationLink) {
	*out = *in
	if in.KeyRangeFilter != nil {
		in, out := &in.KeyRangeFilter, &out.KeyRangeFilter
		*out = new(KeyRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationLink.
func (in *ReplicationLink) DeepCopy() *ReplicationLink {
	if in == nil {
		return nil
	}
	out := new(ReplicationLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationLinkStatus) DeepCopyInto(out *ReplicationLinkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationLinkStatus.
func (in *ReplicationLinkStatus) DeepCopy() *ReplicationLinkStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationLinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReshardSeedTable) DeepCopyInto(out *ReshardSeedTable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReshardSeedTable.
func (in *ReshardSeedTable) DeepCopy() *ReshardSeedTable {
	if in == nil {
		return nil
	}
	out := new(ReshardSeedTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoredFrom) DeepCopyInto(out *RestoredFrom) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoredFrom.
func (in *RestoredFrom) DeepCopy() *RestoredFrom {
	if in == nil {
		return nil
	}
	out := new(RestoredFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionSpec) DeepCopyInto(out *RetentionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionSpec.
func (in *RetentionSpec) DeepCopy() *RetentionSpec {
	if in == nil {
		return nil
	}
	out := new(RetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterCounts) DeepCopyInto(out *RouterCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterCounts.
func (in *RouterCounts) DeepCopy() *RouterCounts {
	if in == nil {
		return nil
	}
	out := new(RouterCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterSpec) DeepCopyInto(out *RouterSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterSpec.
func (in *RouterSpec) DeepCopy() *RouterSpec {
	if in == nil {
		return nil
	}
	out := new(RouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingEndpoint) DeepCopyInto(out *RoutingEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingEndpoint.
func (in *RoutingEndpoint) DeepCopy() *RoutingEndpoint {
	if in == nil {
		return nil
	}
	out := new(RoutingEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingGate) DeepCopyInto(out *RoutingGate) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	in.Deadline.DeepCopyInto(&out.Deadline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingGate.
func (in *RoutingGate) DeepCopy() *RoutingGate {
	if in == nil {
		return nil
	}
	out := new(RoutingGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingSequence) DeepCopyInto(out *RoutingSequence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingSequence.
func (in *RoutingSequence) DeepCopy() *RoutingSequence {
	if in == nil {
		return nil
	}
	out := new(RoutingSequence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingShard) DeepCopyInto(out *RoutingShard) {
	*out = *in
	out.KeyRange = in.KeyRange
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(RoutingEndpoint)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]RoutingEndpoint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingShard.
func (in *RoutingShard) DeepCopy() *RoutingShard {
	if in == nil {
		return nil
	}
	out := new(RoutingShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingTable) DeepCopyInto(out *RoutingTable) {
	*out = *in
	if in.Sequences != nil {
		in, out := &in.Sequences, &out.Sequences
		*out = make([]RoutingSequence, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingTable.
func (in *RoutingTable) DeepCopy() *RoutingTable {
	if in == nil {
		return nil
	}
	out := new(RoutingTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SequenceEntry) DeepCopyInto(out *SequenceEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SequenceEntry.
func (in *SequenceEntry) DeepCopy() *SequenceEntry {
	if in == nil {
		return nil
	}
	out := new(SequenceEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardCounts) DeepCopyInto(out *ShardCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardCounts.
func (in *ShardCounts) DeepCopy() *ShardCounts {
	if in == nil {
		return nil
	}
	out := new(ShardCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardsSpec) DeepCopyInto(out *ShardsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardsSpec.
func (in *ShardsSpec) DeepCopy() *ShardsSpec {
	if in == nil {
		return nil
	}
	out := new(ShardsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeOverrides) DeepCopyInto(out *SizeOverrides) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ReplicasPerShard != nil {
		in, out := &in.ReplicasPerShard, &out.ReplicasPerShard
		*out = new(int32)
		**out = **in
	}
	if in.Synchronous != nil {
		in, out := &in.Synchronous, &out.Synchronous
		*out = new(SynchronousSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeOverrides.
func (in *SizeOverrides) DeepCopy() *SizeOverrides {
	if in == nil {
		return nil
	}
	out := new(SizeOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeSpec) DeepCopyInto(out *SizeSpec) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(SizeOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeSpec.
func (in *SizeSpec) DeepCopy() *SizeSpec {
	if in == nil {
		return nil
	}
	out := new(SizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynchronousSpec) DeepCopyInto(out *SynchronousSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynchronousSpec.
func (in *SynchronousSpec) DeepCopy() *SynchronousSpec {
	if in == nil {
		return nil
	}
	out := new(SynchronousSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemSpec) DeepCopyInto(out *SystemSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemSpec.
func (in *SystemSpec) DeepCopy() *SystemSpec {
	if in == nil {
		return nil
	}
	out := new(SystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableEntry) DeepCopyInto(out *TableEntry) {
	*out = *in
	if in.Sequences != nil {
		in, out := &in.Sequences, &out.Sequences
		*out = make([]RoutingSequence, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableEntry.
func (in *TableEntry) DeepCopy() *TableEntry {
	if in == nil {
		return nil
	}
	out := new(TableEntry)
	in.DeepCopyInto(out)
	return out
}
