# This rule is not used by the project pgshard itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to pgshard.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pgshard
    app.kubernetes.io/managed-by: kustomize
  name: pgshardrouting-viewer-role
rules:
- apiGroups:
  - pgshard.dev
  resources:
  - pgshardroutings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pgshard.dev
  resources:
  - pgshardroutings/status
  verbs:
  - get
