---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgshard.dev
  resources:
  - pgshardclusters
  - pgshardnodes
  - pgshardshards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgshard.dev
  resources:
  - pgshardclusters/finalizers
  - pgshardnodes/finalizers
  - pgshardshards/finalizers
  verbs:
  - update
- apiGroups:
  - pgshard.dev
  resources:
  - pgshardclusters/status
  - pgshardnodes/status
  - pgshardshards/status
  verbs:
  - get
  - patch
  - update
