## Append samples of your project ##
resources:
- pgshard_v1alpha1_pgshardcluster.yaml
- pgshard_v1alpha1_pgshardshard.yaml
- pgshard_v1alpha1_pgshardrouting.yaml
- pgshard_v1alpha1_pgshardtableconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
