apiVersion: pgshard.dev/v1alpha1
kind: PgShardCluster
metadata:
  labels:
    app.kubernetes.io/name: pgshard
    app.kubernetes.io/managed-by: kustomize
  name: pgshardcluster-sample
spec:
  # TODO(user): Add fields here
